export interface LayoverGuide {
  airport: string;
  city: string;
  flag: string;
  tips: { icon: string; title: string; desc: string }[];
  lounges?: string;
  transitVisa?: string;
  cityImage?: string; // Unsplash photo ID
}

const GUIDES: Record<string, LayoverGuide> = {
  MIA: {
    airport: 'Miami International Airport',
    city: 'Miami',
    flag: '🇺🇸',
    lounges: 'The Club at MIA (pay ~$45, T2/D); American Airlines Admirals Club (AA members/first class)',
    tips: [
      { icon: '🌊', title: 'Wynwood or beach?', desc: 'Wynwood street art murals are 20 min by Uber. South Beach is 30 min.' },
      { icon: '🍖', title: 'Cuban food airside', desc: 'Versailles Cuban Café in T2 (post-security) — ropa vieja and cortadito worth the stop.' },
      { icon: '🚌', title: 'To downtown quick', desc: 'MIA Mover train (free) to Rental Car Center, then Miami-Dade transit bus.' },
    ],
  },
  DFW: {
    airport: 'Dallas/Fort Worth International Airport',
    city: 'Dallas',
    flag: '🇺🇸',
    lounges: 'American Airlines Admirals Club (AA members/first class); The Club at DFW T2 (pay ~$45)',
    tips: [
      { icon: '🤠', title: 'World\'s 2nd busiest', desc: 'DFW is massive — allow 30+ min between gates in different terminals. Skylink train is fast.' },
      { icon: '🥩', title: 'Texas BBQ', desc: 'Cousin\'s Bar-B-Q in T3 and T4. Get the brisket. It\'s legitimately good airport food.' },
      { icon: '🚶', title: 'Skylink is free', desc: 'The automated train runs 24h between all terminals. Fast and reliable.' },
    ],
  },
  JFK: {
    airport: 'John F. Kennedy International Airport',
    city: 'New York',
    flag: '🇺🇸',
    cityImage: 'photo-1496442226666-8d4d0e62e6e9',
    lounges: 'The Centurion Lounge T4 (Amex Platinum/pay ~$50); Delta Sky Club T4 (Delta card/SkyMiles); TWA Hotel rooftop (non-lounge, pay)',
    tips: [
      { icon: '🗽', title: 'NYC in 60 min', desc: 'AirTrain to Jamaica, then LIRR or subway to Manhattan — ~$12 total. Uber is $60–90.' },
      { icon: '🕐', title: 'Terminal gaps are real', desc: 'Different terminals require going through security again. Budget extra time.' },
      { icon: '🍕', title: 'NYC pizza pre-flight', desc: 'T4 has Shake Shack and Whitmans — solid compared to most airports.' },
    ],
  },
  LAX: {
    airport: 'Los Angeles International Airport',
    city: 'Los Angeles',
    flag: '🇺🇸',
    lounges: 'The Centurion Lounge T4 (Amex Platinum/pay); Star Alliance Business Lounge T2 (Star Alliance Business+)',
    tips: [
      { icon: '🚗', title: 'Traffic is brutal', desc: 'Add 30–60 min buffer to any airport transfer. Fly by app (FlyAway) is the most reliable.' },
      { icon: '🌴', title: 'Tom Bradley is nicest', desc: 'TBIT (international terminal) is the most modern and has the best food options.' },
      { icon: '🍣', title: 'Sugarfish airside', desc: 'Sugarfish in TBIT — legit sushi before a long-haul.' },
    ],
  },
  GIG: {
    airport: 'Rio de Janeiro–Galeão International Airport',
    city: 'Rio de Janeiro',
    flag: '🇧🇷',
    cityImage: 'photo-1483729558449-99ef09a8c325',
    lounges: 'Gol Smiles Lounge T1 (Gol members/pay ~$30); VIP Lounge T2 (pay ~$30, includes buffet)',
    tips: [
      { icon: '🏖️', title: 'Copacabana is 45 min', desc: 'Taxi or app (99/Uber) to Zona Sul is R$80–120. BRT bus from airport is cheap but slow.' },
      { icon: '🔒', title: 'Safety first', desc: 'Use ride-apps, not unmarked taxis. Don\'t display phones or cameras on arrival plaza.' },
      { icon: '🥤', title: 'Coconut water airside', desc: 'Fresh coconut at the kiosks in T2 is genuinely good and cheaper than coffee.' },
    ],
  },
  GRU: {
    airport: 'São Paulo/Guarulhos International Airport',
    city: 'São Paulo',
    flag: '🇧🇷',
    lounges: 'LATAM VIP Lounge T2 (LATAM Business+); GRU Airport VIP Lounge (pay ~$40); Smiles Lounge (pay)',
    tips: [
      { icon: '🏙️', title: 'São Paulo is 1h away', desc: 'CON shuttle or Uber (~R$100–140) to Paulista. Allow 1.5h in rush hour.' },
      { icon: '☕', title: 'Best coffee in South America', desc: 'Brazil is the world\'s largest coffee producer — the espresso in T3 kiosks is exceptional.' },
    ],
  },
  BOG: {
    airport: 'El Dorado International Airport',
    city: 'Bogotá',
    flag: '🇨🇴',
    lounges: 'Copa Airlines Business Lounge (Copa First/Business); El Dorado VIP Lounge (pay ~$35); Avianca VIP Lounge (Avianca LifeMiles Elite)',
    tips: [
      { icon: '☕', title: 'World\'s best coffee here', desc: 'Colombia is the home of single-origin specialty coffee. Get a tinto before your flight — it\'s exceptional.' },
      { icon: '🌆', title: 'Bogotá at 2,600m altitude', desc: 'The city sits at high altitude — drink water, skip alcohol your first day.' },
      { icon: '🚕', title: 'InDriver or Cabify', desc: 'Use ride apps. Official taxis from the booth are safe, avoid unmarked vehicles.' },
    ],
  },
  MEX: {
    airport: 'Mexico City International Airport',
    city: 'Mexico City',
    flag: '🇲🇽',
    lounges: 'Aeromexico Salon Premier (Aeromexico Platinum/Business); TACA VIP Lounge (pay ~$30)',
    tips: [
      { icon: '🌮', title: 'Best tacos of your life', desc: 'Tacos de canasta in the departure hall. Sound questionable, taste unreal.' },
      { icon: '🚇', title: 'Metro is $0.25', desc: 'Terminal 1 has a metro station — cheapest ride into the city (35 min to Zócalo).' },
    ],
  },
  LIM: {
    airport: 'Jorge Chávez International Airport',
    city: 'Lima',
    flag: '🇵🇪',
    lounges: 'LATAM VIP Lounge (LATAM Business); VIP Lounge LIM (pay ~$35, airside)',
    tips: [
      { icon: '🍽️', title: 'Astrid y Gastón nearby', desc: 'Lima is the fine-dining capital of Latin America. Even airport food options are surprisingly good.' },
      { icon: '🌫️', title: 'Lima is grey', desc: 'The city is covered in fog (garúa) June–November. Don\'t judge by the sky — it\'s one of South America\'s best cities.' },
    ],
  },
  SCL: {
    airport: 'Arturo Merino Benítez International Airport',
    city: 'Santiago',
    flag: '🇨🇱',
    lounges: 'Sala VIP Sky (Sky Airline members); LATAM Lounge (LATAM Business/Elite); Sala VIP Lan Chile (pay ~$35)',
    tips: [
      { icon: '🏔️', title: 'Andes views from the plane', desc: 'Window seat on right side landing from north — Aconcagua (7000m) is stunning on clear days.' },
      { icon: '🍷', title: 'Chilean wine in the lounge', desc: 'SCL lounges stock decent Carménère and Malbec — take advantage before a long haul.' },
    ],
  },
  BKK: {
    airport: 'Suvarnabhumi Airport',
    city: 'Bangkok',
    flag: '🇹🇭',
    cityImage: 'photo-1528360983277-13d401cdc186',
    lounges: 'Coral Executive Lounge (airside, pay at door ~$35)',
    transitVisa: 'Transit visa-free up to 24h for most passports',
    tips: [
      { icon: '🍜', title: 'Food hall (Level 3–4)', desc: 'Huge food court with full Thai meals from $3. Open 24h. Try the boat noodles or pad see ew.' },
      { icon: '💆', title: 'Massage (Level 4)', desc: 'Thai massage shops airside — foot massage from $15/hr. Perfect for a long wait.' },
      { icon: '🏙️', title: 'Slip into Bangkok (4h+)', desc: 'BTS/taxi 30 min to city. Grab a quick street food meal on Sukhumvit. Come back well before boarding.' },
      { icon: '🛍️', title: 'King Power duty-free', desc: 'Large duty-free complex. Thai snacks, cosmetics, watches. Open 24h.' },
      { icon: '🛏️', title: 'Sleep pods (Novotel)', desc: 'Novotel is connected airside. Day-use rooms available by the hour for naps.' },
    ],
  },
  DMK: {
    airport: 'Don Mueang Airport',
    city: 'Bangkok',
    flag: '🇹🇭',
    lounges: 'Miracle Lounge (pay ~$28)',
    tips: [
      { icon: '🍜', title: 'Thai food court', desc: 'Cheap and excellent Thai food in the main terminal. Pad thai from $2.' },
      { icon: '🏪', title: '7-Eleven & shops', desc: 'Convenience stores everywhere for snacks, drinks, and travel essentials.' },
      { icon: '🏙️', title: 'Quick Bangkok trip (4h+)', desc: 'Grab a taxi (~$8) or van to Chatuchak market. Only 20 min away.' },
    ],
  },
  DXB: {
    airport: 'Dubai International',
    city: 'Dubai',
    flag: '🇦🇪',
    cityImage: 'photo-1512453979798-5ea266f8880c',
    lounges: 'Marhaba Lounge (pay ~$50); free if flying Emirates Business+',
    transitVisa: 'Free 48h transit visa for most nationalities if connecting via Emirates',
    tips: [
      { icon: '🛍️', title: 'Duty-free mall', desc: 'One of the largest in the world. Perfume, electronics, gold jewellery, alcohol. Open 24h.' },
      { icon: '🍽️', title: 'Eating options', desc: 'Huge food court with global options. Budget: Shake Shack or local wraps ($10–15). Nice: options throughout all terminals.' },
      { icon: '🛏️', title: 'Sleep & shower (G Hotel)', desc: 'G hotel connected airside for naps by the hour. Showers also available.' },
      { icon: '🏙️', title: 'See Dubai (6h+)', desc: 'Uber to Dubai Mall (~30 min, ~$20). Burj Khalifa views, indoor ski slope, aquarium. Worth it for long stops.' },
      { icon: '💱', title: 'Currency exchange', desc: 'Best rates at exchange booths in the terminal — better than airport ATMs.' },
    ],
  },
  SIN: {
    airport: 'Changi Airport',
    city: 'Singapore',
    flag: '🇸🇬',
    cityImage: 'photo-1525625293386-3f8f99389edd',
    lounges: 'Ambassador Transit Lounge (24h, pay ~$35, includes food and shower)',
    transitVisa: 'Most passports get free 96h transit without a visa',
    tips: [
      { icon: '🌿', title: 'Jewel Changi (free)', desc: "World's tallest indoor waterfall. Free to enter. Connect via walkway from T1/T2/T3. Grab coffee and watch the waterfall." },
      { icon: '🎬', title: 'Free cinema & entertainment', desc: 'Free 24h movie theater (T3), rooftop pool (T1, fee), butterfly garden (T3). Ranked #1 airport for a reason.' },
      { icon: '🍜', title: 'Food court', desc: 'All terminals have hawker-style food courts with local food from $5. Try chicken rice or laksa.' },
      { icon: '😴', title: 'Free nap zones', desc: 'Dedicated rest areas with reclining chairs in all terminals. Dark, quiet, and free.' },
      { icon: '🏙️', title: 'See Singapore (6h+)', desc: 'MRT from airport is $2. Gardens by the Bay, Marina Bay Sands supertrees, free light show at 8pm.' },
    ],
  },
  DOH: {
    airport: 'Hamad International Airport',
    city: 'Doha',
    flag: '🇶🇦',
    lounges: 'Al Mourjan Business Lounge (pay ~$60); one of the best in the world',
    transitVisa: 'Free transit visa for most nationalities connecting via Qatar Airways',
    tips: [
      { icon: '🐻', title: 'Lamp Bear sculpture', desc: "18-foot Urs Fischer bear in the terminal. Great photo spot — it's become the airport's icon." },
      { icon: '🍽️', title: 'ORYX rotunda', desc: 'Central dining area with global options. All price ranges, open 24h. Qatar cuisine is worth trying.' },
      { icon: '🏊', title: 'Shower & sleep (Oryx Airport Hotel)', desc: 'Airside 5-star hotel — day rooms available. Access to pool for a fee (~$40/3h).' },
      { icon: '🛍️', title: 'Duty-free shopping', desc: 'Luxury brands and local souvenirs. Good prices on perfume, dates, and Arabic sweets.' },
      { icon: '🏙️', title: 'Doha day trip (6h+)', desc: 'Taxi ~20 min to Souq Waqif, the old market. Shisha, food, culture. Returns easy.' },
    ],
  },
  AMS: {
    airport: 'Amsterdam Schiphol',
    city: 'Amsterdam',
    flag: '🇳🇱',
    lounges: 'KLM Crown Lounge (KLM Business/Elite only); Schiphol Airport VIP Lounge (pay)',
    transitVisa: 'Schengen — most nationalities need no visa for short connections',
    tips: [
      { icon: '🎨', title: 'Rijksmuseum annex (free)', desc: 'A small but real Rijksmuseum branch is airside between piers E and F. Free entry, original Dutch masters.' },
      { icon: '🌷', title: 'Flower market', desc: 'Buy tulip bulbs and Dutch flowers to take home — airside, past security.' },
      { icon: '🍺', title: 'Heineken bar (airside)', desc: 'Proper Dutch brown café atmosphere. Try the local beer or jenever (Dutch gin).' },
      { icon: '🏙️', title: 'Amsterdam day trip (4h+)', desc: 'Direct train from Schiphol to Amsterdam Centraal — 17 minutes, $5. Canal walks, Anne Frank House, pancakes.' },
      { icon: '🚲', title: 'Bike rental (4h+)', desc: 'Rent a bike at Centraal station ($15/day) and cycle the canals. Quintessential Amsterdam.' },
    ],
  },
  LHR: {
    airport: 'London Heathrow',
    city: 'London',
    flag: '🇬🇧',
    cityImage: 'photo-1513635269975-59663e0ac1ad',
    lounges: 'No1 Lounge T2/T3 (pay ~$60); Plaza Premium (T2/T3/T4, pay)',
    transitVisa: 'UK Transit Visa required for some nationalities — check before you fly',
    tips: [
      { icon: '🍺', title: 'Gordon Ramsay Plane Food (T5)', desc: 'Celebrity chef restaurant airside at T5. Not cheap but a memorable meal.' },
      { icon: '🛍️', title: 'Harrods departure shop', desc: 'Airside Harrods store for iconic British gifts — shortbread, tea, scarves.' },
      { icon: '🏙️', title: 'London day trip (5h+)', desc: 'Piccadilly line train — 50 min to central London (~$7). Hyde Park, British Museum (free), Covent Garden.' },
      { icon: '🛏️', title: 'Sleep options', desc: 'Yotel is airside at T4 — small pods by the hour for naps. Affordable and clean.' },
      { icon: '💷', title: 'Currency note', desc: 'UK uses GBP, not Euros. Tap-to-pay works everywhere including the tube.' },
    ],
  },
  IST: {
    airport: 'Istanbul Airport',
    city: 'Istanbul',
    flag: '🇹🇷',
    lounges: 'IGA Lounge (pay ~$45, includes unlimited food and drinks)',
    transitVisa: 'Most nationalities can transit visa-free up to 24h',
    tips: [
      { icon: '☕', title: 'Turkish coffee & baklava', desc: 'Excellent Turkish coffee shops throughout. Get a Turkish tea (çay) from $1 and baklava from the dessert shops.' },
      { icon: '🛍️', title: 'Duty-free is massive', desc: 'One of Europe\'s largest duty-free malls. Electronics, clothes, food — prices are genuinely good.' },
      { icon: '🏙️', title: 'Istanbul day trip (5h+)', desc: 'Airport bus to city (~$5, 45 min). Hagia Sophia, Grand Bazaar, Bosphorus views — iconic 2h circuit.' },
      { icon: '💆', title: 'Turkish hammam (airside)', desc: 'Some terminals have actual hammam spa experience. Unique to Istanbul airport.' },
      { icon: '🌙', title: 'Open 24h — night stops fine', desc: 'Full food, shops, and lounges available around the clock. Good airport for red-eye connections.' },
    ],
  },
  FRA: {
    airport: 'Frankfurt Airport',
    city: 'Frankfurt',
    flag: '🇩🇪',
    lounges: 'Lufthansa Business Lounge (pay if non-Lufthansa); several pay lounges',
    tips: [
      { icon: '🍺', title: 'German beer (airside)', desc: 'Proper German beer halls in the terminal. Weizen and pretzels from morning. Very German.' },
      { icon: '🚂', title: 'ICE trains from airport', desc: 'Frankfurt Fernbahnhof is connected — ICE trains to Cologne, Munich, Stuttgart. Great for longer stops.' },
      { icon: '🏙️', title: 'Frankfurt in 3h', desc: 'S-Bahn 10 min to city centre. Römerberg old town, apple wine bars. Clean, easy city to navigate.' },
      { icon: '🛍️', title: 'Passenger Terminal 1 mall', desc: 'Full shopping mall airside — clothes, books, electronics, pharmacies.' },
    ],
  },
  FCO: {
    airport: 'Rome Fiumicino (Leonardo da Vinci) Airport',
    city: 'Rome',
    flag: '🇮🇹',
    cityImage: 'photo-1552832230-c0197dd311b5',
    lounges: 'Sala Alata Lounge T3 (pay ~€35, includes food and drinks); Air France/KLM Lounge T3 (Sky Priority/Business)',
    tips: [
      { icon: '🍕', title: 'Real pizza in Rome (45 min)', desc: 'Leonardo Express train to Termini station is 32 min (€14). Campo de\' Fiori and Trastevere are 15 min walk — get a pizza al taglio from any bakery, not sit-down.' },
      { icon: '🚆', title: 'Leonardo Express', desc: 'Non-stop train from FCO to Roma Termini every 15 min. Buy at the machine to avoid queues. Runs 06:23–23:23.' },
      { icon: '🍝', title: 'Pasta vs tourist traps', desc: 'Avoid restaurants near Trevi Fountain and the Colosseum — they charge 3× the price. Walk 2 blocks in any direction for real local spots.' },
      { icon: '🗣️', title: 'Language', desc: 'Italian. Ciao (hi/bye), Grazie (thanks), Per favore (please), Dov\'è il bagno? (Where\'s the toilet?). Most airport staff speak English.' },
    ],
  },
  TLV: {
    airport: 'Ben Gurion International Airport',
    city: 'Tel Aviv',
    flag: '🇮🇱',
    cityImage: 'photo-1544967082-d9d25d867d66',
    lounges: 'El Al King David Lounge T3 (El Al Business/Platinum); Fattal Priority Lounge T3 (pay ~$40, includes hot food); Plaza Premium Lounge T3 (pay ~$45)',
    tips: [
      { icon: '🏖️', title: 'Tel Aviv beach (25 min)', desc: 'Sherut (shared taxi) from the airport is ~₪30, runs at all hours. The promenade between Jaffa and Gordon Beach is iconic — perfect for a layover.' },
      { icon: '🧆', title: 'Hummus for breakfast', desc: 'Abu Hassan in Jaffa or HaKosem in central Tel Aviv — Israelis eat hummus in the morning and it\'s a cultural experience. Open early.' },
      { icon: '🔐', title: 'Security is thorough', desc: 'Ben Gurion has the world\'s most rigorous airport security. Allow 3h+ before your flight, especially non-Israeli passport holders. Questions are standard.' },
      { icon: '🗣️', title: 'Language', desc: 'Hebrew and Arabic. Shalom (hello/goodbye/peace), Toda (thanks), Bevakasha (please/you\'re welcome). English is very widely spoken — you\'ll have no trouble.' },
    ],
  },
  CDG: {
    airport: 'Paris Charles de Gaulle',
    city: 'Paris',
    flag: '🇫🇷',
    cityImage: 'photo-1502602898657-3e91760cbb34',
    lounges: 'Air France Salon (pay for non-AF pax); Club CDG (pay)',
    tips: [
      { icon: '🥐', title: 'Croissant & espresso', desc: 'Multiple proper French café/bakeries airside. Get a proper café crème and croissant. Non-negotiable.' },
      { icon: '🍷', title: 'French wine bar', desc: 'Several wine bars with excellent French regional wines by the glass. $8–12/glass but worth it.' },
      { icon: '🏙️', title: 'Paris (4h+)', desc: 'RER B train — 30 min to city (~$15). Montmartre or Marais neighbourhood are walkable, iconic, and close.' },
      { icon: '😤', title: 'Allow extra time', desc: 'CDG is enormous with confusing terminal layout. T2 connections can take 45+ min. Don\'t cut it tight.' },
    ],
  },
  NRT: {
    airport: 'Tokyo Narita',
    city: 'Tokyo',
    flag: '🇯🇵',
    cityImage: 'photo-1540959733332-eab4deabeeaf',
    lounges: 'IASS Executive Lounge (pay ~$30 with shower)',
    transitVisa: 'Most nationalities can transit without visa for 24–72h',
    tips: [
      { icon: '🍱', title: 'Japanese food court', desc: 'Excellent ramen, sushi, tonkatsu from $8–15. Quality is high even in the airport. Try the tonkotsu ramen.' },
      { icon: '🛁', title: 'Capsule hotel & onsen', desc: '9h Hotel Narita is a 5-min shuttle — capsule rooms with access to proper Japanese hot spring bath.' },
      { icon: '🚅', title: 'Tokyo in 60 min', desc: 'Narita Express to Shinjuku (~$28, 60 min) or cheaper Skyliner. Worth it for 6h+ stops.' },
      { icon: '🛍️', title: 'Japanese convenience store', desc: 'FamilyMart and 7-Eleven in the terminal — onigiri, hot food, drinks at Japanese prices. Amazing value.' },
      { icon: '🎎', title: 'Cultural zone (T2)', desc: 'T2 has a small Japanese garden and art installations. Peaceful area to decompress.' },
    ],
  },
  HKG: {
    airport: 'Hong Kong International',
    city: 'Hong Kong',
    flag: '🇭🇰',
    lounges: 'Plaza Premium Lounge (pay ~$40 with shower and buffet)',
    transitVisa: 'Visa-free transit for most nationalities',
    tips: [
      { icon: '🍜', title: 'Dim sum airside', desc: 'Crystal Jade and other proper HK dim sum restaurants airside. Get the har gow and char siu bao.' },
      { icon: '🏙️', title: 'Hong Kong in 30 min', desc: 'Airport Express to Kowloon — 19 min ($14). Nathan Road, Temple Street night market if arriving evening.' },
      { icon: '🛍️', title: 'SkyPlaza mall', desc: 'Connected mall with 35+ shops. Electronics are sometimes cheaper than downtown.' },
      { icon: '🛁', title: 'Shower facilities', desc: 'Shower facilities available at Plaza Premium — $25 including towel and amenities.' },
    ],
  },
  PTY: {
    airport: 'Tocumen International Airport',
    city: 'Panama City',
    flag: '🇵🇦',
    lounges: 'Copa Airlines VIP Lounge (Copa Gold/Business or pay ~$45); Miraflores Lounge (pay ~$35, walk-in, food included)',
    tips: [
      { icon: '🛋️', title: 'Copa hub — great lounges', desc: 'PTY is Copa\'s main hub. The Copa VIP Lounge (near gate 17) is one of the best value lounges in Latin America — pay access is worth it for long layovers.' },
      { icon: '🌊', title: 'Panama Canal (4h+)', desc: 'Miraflores Locks visitor centre is 30 min by taxi (~$25). Watch ships transit the canal — genuinely stunning engineering.' },
      { icon: '🏙️', title: 'Casco Viejo (4h+)', desc: 'Panama City\'s UNESCO old town is 40 min by taxi (~$30). Colourful colonial buildings, rooftop bars, and incredible Pacific views.' },
      { icon: '💵', title: 'USD everywhere', desc: 'Panama uses the US dollar — no currency exchange needed.' },
    ],
  },
  ASU: {
    airport: 'Silvio Pettirossi International Airport',
    city: 'Asunción',
    flag: '🇵🇾',
    lounges: 'VIP Lounge ASU (pay ~$25, walk-in, includes snacks); GOL Lounge (GOL members)',
    tips: [
      { icon: '💰', title: 'One of South America\'s cheapest cities', desc: 'Asunción is extremely affordable. Everything from food to taxis costs half what you\'d pay in Brazil or Argentina.' },
      { icon: '🏛️', title: 'Centro Histórico (3h+)', desc: 'Taxi ~20 min to the old town (~$10). Palacio de los López and the waterfront Costanera are worth the quick visit.' },
      { icon: '🥩', title: 'Paraguayan beef', desc: 'Paraguay has some of the best beef in South America. A proper churrasco in the airport food hall is cheap and excellent.' },
    ],
  },
  EZE: {
    airport: 'Ministro Pistarini International Airport (Ezeiza)',
    city: 'Buenos Aires',
    flag: '🇦🇷',
    lounges: 'Aerolíneas Argentinas Cóndor Lounge (AR Business/Gold or pay ~$35); VIP Lounge EZE Terminal A (pay ~$30, walk-in, food & drinks included)',
    tips: [
      { icon: '🛋️', title: 'Walk-in lounge — worth every peso', desc: 'The VIP Lounge in Terminal A costs ~$30 walk-in and includes hot food, wine, and showers. Far better than the terminal food courts for a 7h layover.' },
      { icon: '🥩', title: 'Buenos Aires steak (4h+)', desc: 'Palermo or San Telmo are 45 min by taxi (~$20). A proper Argentine asado lunch runs $15–25. One of the best meals you\'ll have at any layover destination.' },
      { icon: '🏙️', title: 'Puerto Madero (3h+)', desc: 'The revamped waterfront is 30 min from EZE. Upscale restaurants, a walking boardwalk, and easy taxi return — the most time-efficient city visit from the airport.' },
      { icon: '💃', title: 'San Telmo tango & market', desc: 'San Telmo market has street tango performances on weekends and great leather shops. Free to watch — an authentic Buenos Aires snapshot in under 2 hours on the ground.' },
      { icon: '💵', title: 'Use your foreign card at the ATM', desc: 'Argentina\'s "blue rate" gives foreign cards significantly better exchange than official rate. Withdraw ARS from the EZE airport ATM for the best legal rate before heading into the city.' },
    ],
  },
  SAL: {
    airport: 'Monseñor Óscar Arnulfo Romero International Airport',
    city: 'San Salvador',
    flag: '🇸🇻',
    lounges: 'Avianca VIP Lounge (Avianca Business/LifeMiles Gold+); Executive Lounge SAL (pay ~$30, walk-in, food & drinks)',
    tips: [
      { icon: '🛋️', title: 'Executive Lounge — solid walk-in option', desc: 'SAL has a walk-in Executive Lounge for ~$30. Includes hot food, local beer, and AC — much better than the terminal for a 7h layover.' },
      { icon: '🌋', title: 'Santa Ana volcano (5h+)', desc: 'El Salvador has some of Central America\'s most accessible volcanoes. Santa Ana is 1.5h by taxi (~$40 round trip). Guided hikes to the crater lake are surreal — bring a jacket.' },
      { icon: '🏙️', title: 'San Salvador historic center (3h+)', desc: '20 min by taxi (~$15). The Palacio Nacional, Catedral Metropolitana, and Plaza Barrios are all walkable. The city is smaller and more manageable than most Central American capitals.' },
      { icon: '🍜', title: 'Pupusas — El Salvador\'s national dish', desc: 'SAL\'s food court has decent pupuserías. These thick corn tortillas stuffed with cheese and beans are El Salvador\'s signature dish. Try the revuelta (mixed filling) — $2–3 each.' },
      { icon: '☕', title: 'Salvadoran coffee', desc: 'El Salvador produces excellent coffee. The airport has a local coffee shop serving single-origin Salvadoran beans — arguably better than anything you\'ll find on the plane.' },
    ],
  },
  CLT: {
    airport: 'Charlotte Douglas International Airport',
    city: 'Charlotte',
    flag: '🇺🇸',
    lounges: 'American Airlines Admirals Club (AA status or day pass ~$79); Priority Pass lounges in Concourse E',
    tips: [
      { icon: '🛋️', title: 'Admirals Club — best rest spot', desc: 'CLT is an AA hub so the Admirals Club is well-stocked. Day pass ~$79 or use Priority Pass. Great for a 3h+ layover.' },
      { icon: '🍺', title: 'NC craft beer at the terminal', desc: 'Concourse E has several local NC brewery bars (NoDa, Olde Mecklenburg). Worth trying a local pint — you\'re in one of the best craft beer states.' },
      { icon: '🏙️', title: 'Uptown Charlotte (3h+)', desc: '15 min by taxi (~$25). The NASCAR Hall of Fame, Romare Bearden Park, and the SouthEnd brewery district are all walkable. Good option for a 4h+ layover.' },
      { icon: '🎵', title: 'NASCAR Hall of Fame', desc: 'Only 15 min from the airport. $30 entry. Unique to Charlotte — worth a quick visit if you have 3+ hours and want something different.' },
    ],
  },
  ORD: {
    airport: "O'Hare International Airport",
    city: 'Chicago',
    flag: '🇺🇸',
    lounges: 'United Club (UA status or ~$59 day pass); American Admirals Club; The Club ORD (pay ~$45, any airline)',
    tips: [
      { icon: '🛋️', title: 'The Club ORD — walk-in friendly', desc: 'Terminal 2 has The Club ORD with pay-per-use access (~$45). Hot food, showers, and quiet seating — worth it for a 3h+ layover.' },
      { icon: '🏙️', title: 'Chicago Riverwalk (3h+)', desc: '45 min by Blue Line train ($5). The Riverwalk, Millennium Park, and the Bean are all walking distance from O\'Hare\'s Blue Line stop. Chicago is one of the best airport city trips in the US.' },
      { icon: '🍕', title: 'Deep dish pizza', desc: 'Lou Malnati\'s has a location inside Terminal 3 — grab an authentic Chicago deep dish without leaving the airport.' },
      { icon: '🎨', title: 'Art in the terminal', desc: 'ORD\'s underground tunnel between Concourses B and C has a neon light art installation. Worth the 5-minute walk just to see it.' },
    ],
  },
  ATL: {
    airport: 'Hartsfield-Jackson Atlanta International Airport',
    city: 'Atlanta',
    flag: '🇺🇸',
    lounges: 'Delta Sky Club (DL status or ~$50 day pass); American Express Centurion Lounge (Amex Platinum); Club ATL (pay ~$40)',
    tips: [
      { icon: '🛋️', title: 'Delta Sky Club — ATL\'s best', desc: 'ATL is Delta\'s main hub and the Sky Club here is excellent. Multiple locations across Concourses B, C, D, and F. Day pass ~$50 or Priority Pass.' },
      { icon: '🍑', title: 'Georgia peach everything', desc: 'Almost every restaurant in ATL has a Georgia peach dish or drink. Try the peach sweet tea — it\'s the most "Atlanta" thing you can do in the terminal.' },
      { icon: '🏙️', title: 'Downtown Atlanta (3h+)', desc: '20 min by MARTA train ($2.50). The World of Coca-Cola, Georgia Aquarium, and Centennial Olympic Park are all within walking distance of Peachtree Center station.' },
      { icon: '🚇', title: 'Skybridge — biggest airport in the world', desc: 'ATL has an underground train connecting all 7 concourses. Even if you\'re not going anywhere, riding it end-to-end gives a sense of the scale — it\'s the world\'s busiest airport.' },
    ],
  },
  DEN: {
    airport: 'Denver International Airport',
    city: 'Denver',
    flag: '🇺🇸',
    lounges: 'United Club (UA status or ~$59 day pass); The Club DEN (pay ~$45, Terminal B/C); Centurion Lounge (Amex Platinum)',
    tips: [
      { icon: '🏔️', title: 'Rocky Mountain views from the terminal', desc: 'DEN has floor-to-ceiling mountain views from Concourse B and C. On a clear day you can see the entire Front Range — no need to leave the terminal for a postcard shot.' },
      { icon: '🏙️', title: 'Denver downtown (3h+)', desc: '45 min by A-Line train ($10.50). The 16th Street Mall, LoDo brewery district, and Red Rocks Amphitheatre area are all accessible. Denver is very walkable and worth the trip.' },
      { icon: '🍺', title: 'Colorado craft beer at the gate', desc: 'DEN has several Colorado craft breweries inside (New Belgium, Oskar Blues). Grab a Fat Tire or Dale\'s Pale Ale before your next flight.' },
      { icon: '🎨', title: 'Blue Mustang & airport art', desc: 'DEN is famous for its controversial art — the giant blue horse (Blucifer) outside, plus murals inside the terminal. There\'s even a time capsule not to be opened until 2094.' },
    ],
  },

  // ── China ─────────────────────────────────────────────────────────────────
  PVG: {
    airport: 'Shanghai Pudong International Airport',
    city: 'Shanghai',
    flag: '🇨🇳',
    lounges: 'China Eastern Sky Pearl Lounge T2 (CE Business/Elite; pay ~¥200 walk-in); Plaza Premium Lounge T1 & T2 (pay ~¥350, includes buffet and shower); The Bridge Business Lounge T2 (pay ~¥280)',
    tips: [
      { icon: '🚄', title: 'Maglev — world\'s fastest train to the city', desc: 'The PVG Maglev hits 430 km/h — 8 minutes to Longyang Rd. Worth it just for the experience. Buy tickets at the station below arrivals; transfer to Line 2 metro for Lujiazui (Bund) or Nanjing Rd.' },
      { icon: '💳', title: 'Set up WeChat Pay before your layover', desc: 'Almost nothing in Shanghai accepts Visa or Mastercard. WeChat Pay and Alipay are universal. Link an international card to WeChat Pay at the airport before you leave — food stalls, convenience stores, and taxis all use it.' },
      { icon: '🔒', title: 'VPN: download before you land', desc: 'Google, Instagram, WhatsApp, and most Western apps don\'t work in China. You cannot download a VPN once inside China. Activate it before you board.' },
      { icon: '🏙️', title: 'The Bund & Lujiazui (2h+ layover)', desc: 'If you have 4h+ and no visa issues (China offers 144-hour transit visa-free for many nationalities), The Bund and the Lujiazui skyline are 40 min away. One of the great city views on earth.' },
      { icon: '🍜', title: 'Soup dumplings (xiao long bao)', desc: 'Din Tai Fung has a branch in Terminal 2 — the xiao long bao here are legitimately excellent. If you have a long layover, the original Din Tai Fung in Xintiandi is 50 min away.' },
    ],
  },
  PEK: {
    airport: 'Beijing Capital International Airport',
    city: 'Beijing',
    flag: '🇨🇳',
    lounges: 'Air China First Class Lounge T3E (AC Business+); CNAC Zhejiang Lounge T3 (pay ~¥200, shower included); Plaza Premium T3 (pay ~¥350, buffet and shower); CIP Terminal 3 (pay ~¥380)',
    tips: [
      { icon: '🚇', title: 'Airport Express to the city', desc: 'Line 3 Airport Express runs from T2/T3 to Dongzhimen and Sanyuanqiao — ¥25, 15–25 min. Connects to Lines 2 and 10 for most of Beijing. Far faster than taxis in rush hour.' },
      { icon: '💳', title: 'WeChat Pay & Alipay are essential', desc: 'Beijing is even more cashless than Shanghai. Street food, taxis, and even most malls require WeChat Pay or Alipay. Both accept international Visa/Mastercard — link before you leave the airport.' },
      { icon: '🔒', title: 'VPN required for Google & WhatsApp', desc: 'China\'s Great Firewall blocks Google Maps, WhatsApp, YouTube, and most Western apps. Download and test your VPN before boarding. Baidu Maps and WeChat work as offline alternatives.' },
      { icon: '🏛️', title: 'Forbidden City & Tiananmen (4h+)', desc: 'With a 6h+ layover, you can reach Tiananmen Square and the entrance to the Forbidden City in ~40 min from the airport. Many nationalities qualify for China\'s 144-hour transit visa exemption — check before you fly.' },
    ],
  },
  LIS: {
    airport: 'Humberto Delgado Airport',
    city: 'Lisbon',
    flag: '🇵🇹',
    lounges: 'TAP Premium Lounge (TAP Business/Gold; pay ~€35 walk-in for non-members); Serene Lounge T1 (Priority Pass / pay ~€35, includes food and drinks); No1 Lounges near Gate 41 (pay ~€30, shower available)',
    tips: [
      { icon: '🚇', title: 'Metro to the city in 20 min', desc: 'Red Line (Aeroporto station) runs direct to Alameda and Oriente. Tickets cost ~€1.70 — buy a reloadable Viva Viagem card at the airport machines. The airport is literally on the metro, no bus or taxi needed.' },
      { icon: '🚖', title: 'Taxis & Uber both work well', desc: 'Uber and Bolt are both active at LIS. Official taxis are metered and honest — city centre is roughly €15–20. Avoid unlicensed drivers approaching you in arrivals.' },
      { icon: '🏙️', title: 'Alfama & Belém (3h layover+)', desc: 'With 4–5 hours, you can take the metro to Baixa-Chiado and walk up to Alfama for the viewpoints, or take tram 15E to Belém for the Jerónimos Monastery and famous pastéis de nata at Pastéis de Belém.' },
      { icon: '🌊', title: 'Quick layover tip', desc: 'Even a 2h layover is enough to grab a glass of Portuguese wine and a francesinha in the terminal. LIS is one of the more pleasant European transit airports — modern, spacious, rarely overcrowded.' },
    ],
  },
  MAD: {
    airport: 'Adolfo Suárez Madrid–Barajas Airport',
    city: 'Madrid',
    flag: '🇪🇸',
    lounges: 'Iberia Premium Lounge T4 (Iberia Business/Platinum; pay ~€35); Sala VIP Dali T4 (pay ~€35, Priority Pass accepted, food and showers); American Express Centurion Lounge T4S (Amex Platinum/Centurion only); Sala Cibeles T1–T3 (pay ~€25)',
    tips: [
      { icon: '🚇', title: 'Metro Line 8 to the city', desc: 'Line 8 (pink) runs from all four terminals directly to Nuevos Ministerios in ~12 min and Atocha in ~25 min. A €3 airport supplement is added to the standard fare — total ~€5. Runs 6am–2am daily.' },
      { icon: '🚖', title: 'Bolt and Uber are great here', desc: 'Both Bolt and Uber operate at MAD and are significantly cheaper than official taxis. City centre rides typically run €20–30 depending on traffic. Taxis are also metered and reliable if you prefer.' },
      { icon: '🏛️', title: 'Prado Museum or Retiro Park (4h+)', desc: 'With a long layover, take the metro to Atocha — the Prado Museum is a 5-min walk and arguably Europe\'s finest art collection. Retiro Park is a 10-min walk for a coffee and a stroll. Allow 45 min each way.' },
      { icon: '🍽️', title: 'Terminal 4 food is surprisingly good', desc: 'T4 (the big modern terminal) has proper sit-down restaurants and a good selection of Spanish tapas bars. Skip the grab-and-go chains and look for the Rodilla or Casa Dani options on the upper level.' },
    ],
  },

  // ── Europe (additional) ───────────────────────────────────────────────────
  BCN: {
    airport: 'Barcelona El Prat Airport',
    city: 'Barcelona',
    flag: '🇪🇸',
    cityImage: 'photo-1539037116277-4db20889f2d4',
    lounges: 'Sala VIP El Prat T1 (pay ~€30, Priority Pass); Iberia Lounge T1 (Iberia Business/Gold)',
    tips: [
      { icon: '🚇', title: 'Aerobus or metro', desc: 'Aerobus to Plaça Catalunya is 35 min (€6.75, runs every 5 min). Metro L9 Sud is cheaper (~€5.15 with airport supplement) but requires a transfer at Zona Universitària.' },
      { icon: '🏖️', title: 'Barceloneta beach (3h+)', desc: 'Only 40 min from the airport — take the metro to Barceloneta. La Boqueria market is nearby. Go early: it is overwhelmed by tourists by 10am.' },
      { icon: '🗣️', title: 'Language', desc: 'Catalan and Spanish. Gràcies (thanks in Catalan), Gracias (Spanish), Bon dia (good morning). Speaking a few words of Catalan is appreciated by locals.' },
      { icon: '🥘', title: 'Proper food airside', desc: 'Even BCN airside has decent Spanish food — tortilla española and patatas bravas are available. Skip the international chains.' },
    ],
  },
  MUC: {
    airport: 'Munich Franz Josef Strauss Airport',
    city: 'Munich',
    flag: '🇩🇪',
    lounges: 'Lufthansa Senator/Business Lounge T2 (LH status/Business); No. 1 Lounge T2 (Priority Pass)',
    tips: [
      { icon: '🚆', title: 'S-Bahn to city centre', desc: 'S1 or S8 trains to Marienplatz take ~40 min (€13.60 airport zone ticket). Runs every 20 min from 4am–1am. Buy from machines at the station — no need to queue.' },
      { icon: '🍺', title: 'Hofbräuhaus (3h+)', desc: 'Marienplatz is worth it even for short layovers — the old town is compact and walkable. Hofbräuhaus is 5 min from Marienplatz and a genuine experience, not a tourist trap.' },
      { icon: '🌿', title: 'Terminal 2 indoor garden', desc: 'MUC has a real indoor garden in T2 with actual trees — one of the most relaxing spots in any airport in Europe.' },
      { icon: '🗣️', title: 'Language', desc: 'German (Bavarian dialect). Danke (thanks), Bitte (please), Grüß Gott (hello in Bavaria). Airport staff universally speak English.' },
    ],
  },
  ZRH: {
    airport: 'Zurich Airport',
    city: 'Zurich',
    flag: '🇨🇭',
    lounges: 'Swiss Business Lounge (SWISS Business/Senator; pay ~CHF 60 walk-in); Aspire Lounge (Priority Pass, Terminal E)',
    tips: [
      { icon: '🚆', title: 'Train to city in 10 min', desc: 'Direct train from the airport underground station to Zurich HB runs every 10 min — takes exactly 10 minutes (CHF 7.20). Best airport-to-city train in the world.' },
      { icon: '💰', title: 'Expensive but worth it', desc: 'Zurich is among the priciest cities in the world. A coffee is CHF 5–6, beer CHF 7–9, meal CHF 25+. Budget accordingly if leaving the airport.' },
      { icon: '🏔️', title: 'Altstadt is stunning', desc: 'From Zurich HB it\'s a 10 min walk to the old town. The Lindenhügel viewpoint and Grossmünster church are free and beautiful.' },
      { icon: '🗣️', title: 'Language', desc: 'Swiss German (Züritüütsch), but standard German and English are widely understood. Merci (thanks, even in German-speaking Switzerland), Grüezi (hello).' },
    ],
  },
  VIE: {
    airport: 'Vienna International Airport',
    city: 'Vienna',
    flag: '🇦🇹',
    lounges: 'Austrian Airlines Senator Lounge (OS status/Business); Sky Lounge (pay ~€35, Priority Pass)',
    tips: [
      { icon: '🚆', title: 'CAT express or S-Bahn', desc: 'City Airport Train (CAT) non-stop to Wien Mitte in 16 min (€14.90). S7 train is slower (25 min) but only €4.20 and runs through the centre. Both depart from the same underground station.' },
      { icon: '☕', title: 'Viennese coffee culture', desc: 'Vienna invented the coffeehouse. A Melange (cappuccino) with Sachertorte at any café near the Ringstraße is one of the great simple pleasures. Café Central near Herrengasse is iconic.' },
      { icon: '🎶', title: 'Music capital (4h+)', desc: 'The Staatsoper, Musikverein, and Kunsthistorisches Museum are all within walking distance of the city centre. Even the streets feel like an open-air museum.' },
      { icon: '🗣️', title: 'Language', desc: 'Austrian German. Danke (thanks), Bitte (please), Grüß Gott (formal hello). Viennese take manners seriously — a smile and a Danke goes a long way.' },
    ],
  },
  BRU: {
    airport: 'Brussels Airport',
    city: 'Brussels',
    flag: '🇧🇪',
    lounges: 'Brussels Airlines The Loft (SN Business/Gold); No1 Lounge (Priority Pass, pay ~€30)',
    tips: [
      { icon: '🚆', title: 'Train to city centre', desc: 'Direct trains to Brussels Central, Midi, and Nord run every 15–30 min (€13.40, ~17 min to Brussels Central). Buy tickets at the machines.' },
      { icon: '🍫', title: 'Chocolate & waffles', desc: 'Belgian chocolate is world-class — Neuhaus and Leonidas have airside branches. Brussels waffles (gaufres de Bruxelles) are lighter than the Liège variety — perfect at the airport.' },
      { icon: '🏛️', title: 'Grand-Place (2h+)', desc: 'Brussels Central is a 5 min walk from the Grand-Place — one of the most beautiful town squares in Europe. The Manneken Pis statue is nearby.' },
      { icon: '🗣️', title: 'Language', desc: 'French and Dutch (Flemish). Merci/Dank u (thanks), S\'il vous plaît/Alstublieft (please). French is dominant in Brussels.' },
    ],
  },
  CPH: {
    airport: 'Copenhagen Airport',
    city: 'Copenhagen',
    flag: '🇩🇰',
    lounges: 'SAS Gold Lounge (SAS Gold/Business); No1 Lounge (pay ~DKK 300, Priority Pass)',
    tips: [
      { icon: '🚆', title: 'Metro to city in 15 min', desc: 'M2 metro runs directly to Nørreport (city centre) in 15 min (DKK 36 / ~€5). Runs 24 hours. Buy tickets at the machines in arrivals.' },
      { icon: '🚲', title: 'Bike-friendly city', desc: 'Copenhagen is the world\'s most bike-friendly city. Rent a bike near the station and cycle the harbour front, Nyhavn, or Freetown Christiania — all within 2 km.' },
      { icon: '🍱', title: 'Smørrebrød', desc: 'Danish open-faced sandwiches (smørrebrød) are a cultural institution. Aamans or any konditori near the city does them properly — far better than airport food.' },
      { icon: '🗣️', title: 'Language', desc: 'Danish. Tak (thanks), Vær så god (you\'re welcome), Hej (hi). Nearly every Dane speaks excellent English.' },
    ],
  },
  ARN: {
    airport: 'Stockholm Arlanda Airport',
    city: 'Stockholm',
    flag: '🇸🇪',
    lounges: 'SAS Business Lounge (SAS Gold/Business); Sky City Lounge (pay ~SEK 350, Priority Pass)',
    tips: [
      { icon: '🚆', title: 'Arlanda Express (20 min)', desc: 'Arlanda Express non-stop to Stockholm Central in 20 min (SEK 299 / ~€26). Slower commuter train (~SEK 170 including airport fee) takes 40 min. Both excellent.' },
      { icon: '🌊', title: 'Archipelago city', desc: 'Stockholm sits on 14 islands. Walk along Strandvägen waterfront or take a ferry to Djurgården for the Vasa Museum — the best-preserved 17th-century warship in the world.' },
      { icon: '🎨', title: 'ABBA Museum on Djurgården', desc: '20 min from Central station. Even non-fans find it genuinely entertaining. Book online to skip queues.' },
      { icon: '🗣️', title: 'Language', desc: 'Swedish. Tack (thanks), Förlåt (excuse me), Hej (hi). Swedes have some of the best English in the world.' },
    ],
  },
  HEL: {
    airport: 'Helsinki-Vantaa Airport',
    city: 'Helsinki',
    flag: '🇫🇮',
    lounges: 'Finnair Platinum/Business Lounge (AY status/Business); No1 Lounge (Priority Pass, pay ~€30)',
    tips: [
      { icon: '🚆', title: 'Ring Rail to city', desc: 'I/P trains run every 10 min to Helsinki Central in 30 min (€5.50). The route goes through the forest — very scenic.' },
      { icon: '🧖', title: 'Sauna culture', desc: 'Helsinki has public saunas that are a genuine cultural experience. Löyly and Allas Sea Pool are iconic — entry is ~€25. Silence is respected inside.' },
      { icon: '🌲', title: 'Design and nature', desc: 'Helsinki is known for design (Design District), Temppeliaukio rock church (carved from solid granite), and the market square by the harbour.' },
      { icon: '🗣️', title: 'Language', desc: 'Finnish. Kiitos (thanks), Anteeksi (excuse me). English is excellent — most Finns are fluent.' },
    ],
  },
  OSL: {
    airport: 'Oslo Gardermoen Airport',
    city: 'Oslo',
    flag: '🇳🇴',
    lounges: 'SAS Business Lounge (SAS Gold/Business); Plaza Premium Lounge (Priority Pass, pay ~NOK 400)',
    tips: [
      { icon: '🚆', title: 'Flytoget express (19 min)', desc: 'Flytoget airport express runs every 10 min to Oslo Central in 19 min (NOK 230 / ~€20). Regular NSB trains also run (NOK 116) in 23 min. Both are excellent.' },
      { icon: '🏔️', title: 'Fjord and forest', desc: 'Oslo is surrounded by forests and water. Holmenkollen ski jump has panoramic views year-round — take T-Bane line 1 from Nationaltheatret.' },
      { icon: '💰', title: 'Most expensive city in Europe', desc: 'A beer can be NOK 100+ (€9). Budget significantly more than elsewhere in Europe. Tap water is excellent.' },
      { icon: '🗣️', title: 'Language', desc: 'Norwegian. Takk (thanks), Unnskyld (excuse me), Hei (hi). Norwegians speak outstanding English.' },
    ],
  },
  MAN: {
    airport: 'Manchester Airport',
    city: 'Manchester',
    flag: '🇬🇧',
    lounges: 'Escape Lounge T1 (Priority Pass/pay ~£35); No1 Lounge T3 (Priority Pass/pay ~£35)',
    tips: [
      { icon: '🚆', title: 'Metrolink to city centre', desc: 'Metrolink tram from T1/T2/T3 to Piccadilly Gardens in 25 min (£3.80 off-peak). Direct trains to Manchester Piccadilly in 18 min.' },
      { icon: '⚽', title: 'Football city', desc: 'Old Trafford and Etihad Stadium tours are available most days — book ahead. The National Football Museum is free in the city centre.' },
      { icon: '🍺', title: 'Northern Quarter', desc: 'Independent coffee shops, record stores, and proper northern pubs — 20 min walk from Piccadilly. More authentic than London for a genuine UK experience.' },
      { icon: '🌧️', title: "It does rain", desc: "Manchester's rainfall reputation is somewhat exaggerated, but a light jacket is always wise. The city is famously friendly." },
    ],
  },
  LGW: {
    airport: 'London Gatwick Airport',
    city: 'London',
    flag: '🇬🇧',
    lounges: 'No1 Lounge North/South (pay ~£35, Priority Pass); Aspire Lounge South (Priority Pass)',
    tips: [
      { icon: '🚆', title: 'Gatwick Express (30 min)', desc: 'Gatwick Express non-stop to London Victoria every 15 min (£19.90). Thameslink trains to St Pancras/City are cheaper (£12–17) but stop more. Avoid taxis — very expensive and slow.' },
      { icon: '🏙️', title: 'Further from London than Heathrow', desc: 'LGW is ~45 km south of London. Budget 60–90 min door-to-door to Midtown — allow more at peak hours.' },
      { icon: '🌿', title: 'South terminal is nicer', desc: 'Better lounges, more food options, less congested than the North Terminal.' },
      { icon: '💷', title: 'Currency', desc: 'British Pounds (GBP). ATMs give better rates than currency booths. Use contactless/card everywhere — the UK is very card-friendly.' },
    ],
  },
  MXP: {
    airport: 'Milan Malpensa Airport',
    city: 'Milan',
    flag: '🇮🇹',
    lounges: 'Malpensa Lounge T1 (pay ~€30, Priority Pass); Club SEA T1 (Priority Pass)',
    tips: [
      { icon: '🚆', title: 'Malpensa Express (52 min)', desc: 'Malpensa Express to Milano Cadorna or Centrale runs every 30 min (€13). Buses are cheaper (€8) but subject to traffic — not recommended.' },
      { icon: '🛍️', title: 'Fashion capital', desc: 'Via Montenapoleone and Via della Spiga are the fashion heartland — window-shopping is free. The Quadrilatero della Moda is 10 min from the metro.' },
      { icon: '🎨', title: 'The Last Supper (book ahead)', desc: 'Leonardo\'s Last Supper requires advance booking (weeks ahead). The Pinacoteca di Brera is easier to visit and outstanding.' },
      { icon: '🗣️', title: 'Language', desc: 'Italian. Grazie (thanks), Prego (you\'re welcome), Mi scusi (excuse me). English is less common in Milan than in Rome.' },
    ],
  },
  ATH: {
    airport: 'Athens International Airport (Eleftherios Venizelos)',
    city: 'Athens',
    flag: '🇬🇷',
    lounges: 'Aegean Airlines Lounge (A3 Business/Gold; pay ~€30); Athens Lounge (Priority Pass, T1)',
    tips: [
      { icon: '🚇', title: 'Metro Line 3 to city', desc: 'Metro Line 3 (blue) to Syntagma in 40 min (€10 one-way). Runs 06:30–23:30, every 30 min. Best option — avoid taxis at the airport.' },
      { icon: '🏛️', title: 'Acropolis (3h+ layover)', desc: 'From Syntagma take one metro stop to Monastiraki, walk 15 min up. Buy tickets online — gate queues are long in summer.' },
      { icon: '🥙', title: 'Souvlaki is serious food', desc: 'Monastiraki Square has excellent souvlaki at €2–3 per skewer. Thanasis and Savvas are legendary side-by-side spots. Both are correct.' },
      { icon: '🗣️', title: 'Language', desc: 'Greek. Efharisto (thanks), Parakalo (please/you\'re welcome), Yassas (formal hello). Most Athenians in tourism speak good English.' },
    ],
  },
  PRG: {
    airport: 'Václav Havel Airport Prague',
    city: 'Prague',
    flag: '🇨🇿',
    lounges: 'Czech Airlines Business Lounge T2 (OK Business); Prague Airport Lounge (Priority Pass, pay ~€25)',
    tips: [
      { icon: '🚌', title: 'Bus + metro to centre (~45 min)', desc: 'No direct train. Bus 119 to Nádraží Veleslavín, then Metro A to Wenceslas Square — CZK 40 (~€1.70). One of the cheapest airport connections in Europe.' },
      { icon: '🍺', title: 'World\'s best beer', desc: 'Czech Republic has the highest beer consumption per capita in the world. Pilsner Urquell, Budvar, and Kozel are all Czech originals. A 0.5L Pilsner costs ~€2–3.' },
      { icon: '🌉', title: 'Charles Bridge at sunrise', desc: 'Prague\'s Old Town is overwhelmed by tourists by 9am. Charles Bridge before 7am is magical.' },
      { icon: '🗣️', title: 'Language', desc: 'Czech. Děkuji (thanks), Prosím (please), Dobrý den (good day). English is widespread among younger people.' },
    ],
  },
  BUD: {
    airport: 'Budapest Ferenc Liszt International Airport',
    city: 'Budapest',
    flag: '🇭🇺',
    lounges: 'Sky Court Lounge (Priority Pass, T2B; pay ~€25)',
    tips: [
      { icon: '🚌', title: 'Bus 100E to city centre', desc: 'No direct train — Bus 100E express to Deák Ferenc tér in 35–40 min (HUF 1,500 / ~€4, every 20 min). Or BKK bus 200E + Metro M3 (HUF 750 but slower).' },
      { icon: '♨️', title: 'Thermal baths', desc: 'Budapest has the best thermal baths in Europe. Széchenyi and Gellért are the most famous — entry ~€25 with locker. You can soak in 38°C mineral water.' },
      { icon: '🌉', title: 'Chain Bridge at night', desc: 'Budapest is one of the most beautiful cities in the world after dark. The view from Fisherman\'s Bastion is unforgettable for an evening layover.' },
      { icon: '🗣️', title: 'Language', desc: 'Hungarian (Magyar) — one of the hardest languages. Köszönöm (thanks), Kérem (please), Szia (hi). English is widely spoken in tourist areas.' },
    ],
  },
  WAW: {
    airport: 'Warsaw Chopin Airport',
    city: 'Warsaw',
    flag: '🇵🇱',
    lounges: 'LOT Business Lounge (LO Business/Gold); Business Link Lounge (Priority Pass, pay ~€25)',
    tips: [
      { icon: '🚆', title: 'SKM train to city (25 min)', desc: 'SKM suburban train runs to Warszawa Centralna in 25 min (PLN 4.40 / ~€1 — absurdly cheap). Trains every 15–30 min from a station right at the terminal.' },
      { icon: '🏛️', title: 'Warsaw Old Town', desc: 'Completely destroyed in WWII and rebuilt brick by brick from paintings — UNESCO-listed. The Warsaw Uprising Museum is one of the most powerful war museums in the world.' },
      { icon: '🥟', title: 'Pierogi', desc: 'Polish dumplings are one of the great comfort foods. Ruskie (potato and cheese) or z kapustą i grzybami (cabbage and mushroom). A plate of 10 is ~€6.' },
      { icon: '🗣️', title: 'Language', desc: 'Polish. Dziękuję (thanks), Proszę (please), Cześć (hi). English is common among younger Poles.' },
    ],
  },

  // ── Asia (additional) ─────────────────────────────────────────────────────
  ICN: {
    airport: 'Incheon International Airport',
    city: 'Seoul',
    flag: '🇰🇷',
    cityImage: 'photo-1534274988757-a28bf1a57c17',
    lounges: 'Korean Air Prestige Lounge (KE Business/Elite); Asiana Business Lounge (OZ Business); Sky Hub Lounge (Priority Pass, T1)',
    tips: [
      { icon: '🚆', title: 'AREX express to Seoul', desc: 'All-Stop Train to Seoul Station 55 min (KRW 9,000 / ~$7). Express Train non-stop in 43 min (KRW 11,000). T-money card works on both trains and all Seoul transit.' },
      { icon: '🛏️', title: 'Free transit hotel', desc: 'ICN offers a free 18-hour Transit Hotel for connecting passengers (airside, T1, 5F). Showers are also free for transit passengers.' },
      { icon: '🍜', title: 'Korean BBQ airside', desc: 'ICN has proper Korean food airside. Korean BBQ costs KRW 20,000–40,000. Bibimbap is a lighter option. The galbi-tang at 5F is excellent.' },
      { icon: '🗣️', title: 'Language', desc: 'Korean (Hangul). Gamsahamnida (formal thanks), Annyeonghaseyo (hello). ICN is one of the most foreigner-friendly airports in the world.' },
    ],
  },
  KUL: {
    airport: 'Kuala Lumpur International Airport (KLIA)',
    city: 'Kuala Lumpur',
    flag: '🇲🇾',
    cityImage: 'photo-1596422846543-75c6fc197f07',
    lounges: 'Malaysia Airlines Golden Lounge (MH Business/Enrich Gold); Plaza Premium Lounge (Priority Pass, KLIA/KLIA2)',
    tips: [
      { icon: '🚆', title: 'KLIA Ekspres (28 min)', desc: 'Express train to KL Sentral every 15 min (RM 55 / ~$12). Air-conditioned and comfortable. Best option.' },
      { icon: '🍛', title: 'Best food in Southeast Asia', desc: 'KL hawker food is world-class — nasi lemak, char kway teow, roti canai. The KLIA food court is genuinely good and cheap (under RM 15 for a full meal).' },
      { icon: '🏙️', title: 'Petronas Towers (3h+)', desc: 'LRT from KL Sentral to KLCC (10 min). The free sky bridge viewing platform at floors 41–42 is spectacular. Queue early — limited tickets daily.' },
      { icon: '🗣️', title: 'Language', desc: 'Bahasa Malaysia and English. Terima kasih (thanks), Tolong (please). English is very widely spoken throughout KL.' },
    ],
  },
  DEL: {
    airport: 'Indira Gandhi International Airport',
    city: 'Delhi',
    flag: '🇮🇳',
    lounges: 'Air India Maharaja Lounge T3 (AI Business); Plaza Premium Lounge T3 (Priority Pass, pay ~₹2,500)',
    tips: [
      { icon: '🚇', title: 'Metro to New Delhi station (21 min)', desc: 'Airport Express Metro from T3 to New Delhi in 21 min (₹60 / ~$0.75). Runs 5am–11:30pm. Use Uber/Ola instead of pre-paid taxi booths in arrivals.' },
      { icon: '🌡️', title: 'Heat is serious', desc: 'Delhi in summer (April–July) hits 40–48°C. Drink water constantly. October–February is ideal. Pollution can be significant — check AQI before exploring.' },
      { icon: '🕌', title: 'Old Delhi (3h+)', desc: 'Chandni Chowk is a sensory overload — narrow lanes, spice markets, Jama Masjid, and street food like paratha.' },
      { icon: '🗣️', title: 'Language', desc: 'Hindi and English. Dhanyavaad (formal thanks), Namaste (hello). English is widely used for tourism throughout Delhi.' },
    ],
  },
  BOM: {
    airport: 'Chhatrapati Shivaji Maharaj International Airport',
    city: 'Mumbai',
    flag: '🇮🇳',
    lounges: 'Air India Maharaja Lounge T2 (AI Business); GVK Lounge T2 (Priority Pass, pay ~₹2,000)',
    tips: [
      { icon: '🚇', title: 'Metro or pre-paid taxi', desc: 'Metro Line 1 connects the airport area but doesn\'t go directly to T2. Pre-paid taxi counters inside arrivals are legitimate. Uber/Ola are reliable. Traffic to South Mumbai can take 60–90 min.' },
      { icon: '🌊', title: 'Marine Drive (3h+)', desc: 'The "Queen\'s Necklace" promenade along the Arabian Sea — free, beautiful. Juhu Beach is 20 min from the airport and has great chaat street food.' },
      { icon: '🍛', title: 'Mumbai street food', desc: 'Vada pav (~₹15), pav bhaji, bhel puri at Juhu Beach. The city runs on street food and it\'s safe from reputable stalls.' },
      { icon: '🗣️', title: 'Language', desc: 'Marathi and Hindi, with English widely used. Namaste (hello). Mumbai is one of the most English-friendly cities in India.' },
    ],
  },
  CGK: {
    airport: 'Soekarno-Hatta International Airport',
    city: 'Jakarta',
    flag: '🇮🇩',
    lounges: 'Garuda Indonesia Executive Lounge T3 (GA Business/Platinum); Plaza Premium Lounge T3 (Priority Pass)',
    tips: [
      { icon: '🚆', title: 'Airport train to city', desc: 'Commuter Rail to Duri/Manggarai (~45 min, IDR 70,000 / ~$4.50). Significantly faster than road during peak hours. Uber/Grab available but traffic can be 1–2h to city centre.' },
      { icon: '🌧️', title: 'Monsoon and humidity', desc: 'Jakarta is hot and humid year-round (28–35°C). Rainy season (October–April) brings daily downpours. Stay hydrated.' },
      { icon: '🍜', title: 'Nasi goreng and soto ayam', desc: 'Indonesian food is outstanding — nasi goreng, mie goreng, and soto ayam are everywhere at IDR 20,000–40,000 (~$1.50–3).' },
      { icon: '🗣️', title: 'Language', desc: 'Bahasa Indonesia. Terima kasih (thanks), Tolong (please), Selamat pagi (good morning). English is widely spoken in airports.' },
    ],
  },
  MNL: {
    airport: 'Ninoy Aquino International Airport',
    city: 'Manila',
    flag: '🇵🇭',
    lounges: 'Philippine Airlines Mabuhay Lounge T2 (PR Business); NAIA International Lounge T1 (pay ~₱1,500)',
    tips: [
      { icon: '⚠️', title: 'Allow extra time', desc: 'NAIA is notoriously congested — allow 3h+ before international flights. Traffic from the city can take 1–3h. Grab is the safest transport.' },
      { icon: '🏝️', title: 'Philippines is the destination', desc: 'Manila itself is not a typical sightseeing stop — most use it to connect to Palawan, Cebu, Siargao, or Boracay. Intramuros (old walled city) is worth 2h if stuck.' },
      { icon: '🍚', title: 'Adobo and lechon', desc: 'Chicken/pork adobo, kare-kare (peanut stew), and lechon (roast pig) are the classics. Jollibee (Filipino fast food) is a cultural landmark.' },
      { icon: '🗣️', title: 'Language', desc: 'Filipino (Tagalog) and English. Salamat (thanks), Magandang umaga (good morning). The Philippines has one of the highest English rates in Asia.' },
    ],
  },
  KIX: {
    airport: 'Kansai International Airport',
    city: 'Osaka',
    flag: '🇯🇵',
    lounges: 'JAL Sakura Lounge (JL Business/JGC); ANA Lounge (NH Business/SFC); Annex Lounge (Priority Pass, pay ~¥3,500)',
    tips: [
      { icon: '🚆', title: 'Haruka or Nankai to Osaka/Kyoto', desc: 'Haruka Limited Express to Osaka Station 75 min (¥3,640), Kyoto 80 min (¥3,640). Nankai Rapi:t to Namba 40 min (¥1,450) — better for central Osaka.' },
      { icon: '🍜', title: "Osaka = Japan's food capital", desc: 'Osaka invented takoyaki (octopus balls) and okonomiyaki (savoury pancake). Dotonbori street in Namba — try both at street stalls for under ¥500 each.' },
      { icon: '⛩️', title: 'Kyoto in 80 min (5h+ layover)', desc: 'Fushimi Inari (the 10,000-torii-gate shrine) is a 5-min walk from Inari station — free, open 24h, stunning.' },
      { icon: '🗣️', title: 'Language', desc: 'Japanese. Arigatou (informal thanks), Sumimasen (excuse me), Hai (yes). English signage at KIX is excellent.' },
    ],
  },
  TPE: {
    airport: 'Taiwan Taoyuan International Airport',
    city: 'Taipei',
    flag: '🇹🇼',
    lounges: 'China Airlines Dynasty Lounge (CI Business/Elite); EVA Air Infinity Lounge (BR Business/Elite); Taoyuan Airport VIP Lounge (Priority Pass)',
    tips: [
      { icon: '🚆', title: 'Airport MRT to Taipei (35 min)', desc: 'Non-stop to Taipei Main Station in 35 min (TWD 160 / ~$5). Direct trains every 6 min peak. Buy an easy card — works on all Taipei transit.' },
      { icon: '🌃', title: 'Night markets', desc: 'Taipei night markets are legendary — Shilin is most famous, Raohe is more local. Open 6pm–midnight. Stinky tofu, oyster vermicelli, bubble tea.' },
      { icon: '🏔️', title: 'Jiufen (3h+ from city)', desc: 'The old mining town said to inspire Spirited Away — narrow stone alleys, red lanterns, mountain tea houses. 90 min from Taipei by bus + train.' },
      { icon: '🗣️', title: 'Language', desc: 'Mandarin Chinese (Traditional). Xièxiè (thanks), Nǐ hǎo (hello). English is widely used in Taipei — most signs are bilingual.' },
    ],
  },

  // ── Middle East & Africa ──────────────────────────────────────────────────
  CAI: {
    airport: 'Cairo International Airport',
    city: 'Cairo',
    flag: '🇪🇬',
    lounges: 'EgyptAir Lotus Lounge T3 (MS Business/Lotus Gold); Sama Lounge T2 (Priority Pass, pay ~$30)',
    tips: [
      { icon: '🚕', title: 'Uber or metered taxis', desc: 'Uber works well from CAI (30–60 min to city, ~$6–12). Official white taxis are metered — agree on fare before entering unlicensed cabs. Traffic is heavy at all hours.' },
      { icon: '🏺', title: 'Pyramids of Giza (3h+)', desc: 'The Giza Pyramids are 45 min from the airport — one of the Seven Wonders of the World. Entry is ~$15. Go early morning to avoid crowds and heat.' },
      { icon: '🌡️', title: 'Heat and dress code', desc: 'Cairo summers hit 35–42°C. Lightweight, modest clothing (shoulders and knees covered) is appreciated near mosques and in traditional areas.' },
      { icon: '🗣️', title: 'Language', desc: 'Egyptian Arabic. Shukran (thanks), Min fadlak (please), Ahlan (welcome). English is spoken in tourist areas and hotels.' },
    ],
  },
  AMM: {
    airport: 'Queen Alia International Airport',
    city: 'Amman',
    flag: '🇯🇴',
    lounges: 'Royal Jordanian Crown Lounge (RJ Business/Crown Club Gold); Sama Lounge (Priority Pass, pay ~$30)',
    tips: [
      { icon: '🚕', title: 'JETT bus or taxi', desc: 'JETT Airport Express bus to 7th Circle runs every 30 min (~JOD 3.3 / $5, 45 min). Official taxi ~JOD 20–25 ($28–35) fixed rate. Agree price before entering any unmarked cab.' },
      { icon: '🏛️', title: 'Roman Amphitheatre', desc: 'Downtown Amman has an extraordinarily well-preserved Roman amphitheatre, citadel, and the Jordan Museum (Dead Sea Scrolls) — all within 10 min walk.' },
      { icon: '🥙', title: 'Mansaf and falafel', desc: 'Mansaf (lamb in fermented yogurt sauce with rice) is Jordan\'s national dish. Jordanian falafel and hummus are among the best in the Levant.' },
      { icon: '🗣️', title: 'Language', desc: 'Arabic. Shukran (thanks), Min fadlak (please), Marhaba (hello). English is widely spoken — Amman is one of the most foreigner-friendly Arab capitals.' },
    ],
  },
  AUH: {
    airport: 'Abu Dhabi International Airport',
    city: 'Abu Dhabi',
    flag: '🇦🇪',
    lounges: 'Etihad First & Business Lounge (EY Business/Gold); Marhaba Lounge (Priority Pass, pay ~$40)',
    tips: [
      { icon: '🕌', title: 'Sheikh Zayed Grand Mosque (2h+)', desc: 'One of the most magnificent buildings in the world — 25 min from the airport by taxi (~AED 50). Free entry, modest dress required. Open until midnight.' },
      { icon: '🌡️', title: 'Extreme summer heat', desc: 'Abu Dhabi summers regularly hit 45°C with high humidity. Taxi everywhere rather than walking. October–April is beautiful.' },
      { icon: '🏎️', title: 'Yas Marina Circuit', desc: 'Hosts the Abu Dhabi Grand Prix. Yas Marina waterfront is 20 min from the airport — impressive development with Ferrari World.' },
      { icon: '🗣️', title: 'Language', desc: 'Arabic, but English is used for virtually all business, tourism, and signage. No Arabic needed to navigate Abu Dhabi.' },
    ],
  },
  RUH: {
    airport: 'King Khalid International Airport',
    city: 'Riyadh',
    flag: '🇸🇦',
    lounges: 'Saudia Diamond Lounge (SV Business/Diamond); Al Fursan Lounge (Priority Pass, pay ~SAR 150)',
    tips: [
      { icon: '🚇', title: 'Riyadh Metro or Uber', desc: 'Uber works well in Riyadh (~SAR 50–80 / $14–22 to city centre). The Riyadh Metro (Line 3) is operational and expanding. Avoid unofficial taxis.' },
      { icon: '🏙️', title: 'Kingdom Centre Tower', desc: 'The sky bridge offers panoramic city views (free). Diriyah (the original Saudi capital) is 20 min away and UNESCO-listed.' },
      { icon: '👗', title: 'Dress code has relaxed', desc: 'Saudi Arabia has liberalised significantly — women no longer need abayas in public and tourism is actively welcomed. Modest dress is still appreciated in traditional areas.' },
      { icon: '🗣️', title: 'Language', desc: 'Arabic. Shukran (thanks), Min fadlak (please), As-salamu alaykum (standard greeting). English is widely used in business and hospitality.' },
    ],
  },
  KWI: {
    airport: 'Kuwait International Airport',
    city: 'Kuwait City',
    flag: '🇰🇼',
    lounges: 'Kuwait Airways Lounge (KU Business); Gulf Lounge (Priority Pass, pay ~$35)',
    tips: [
      { icon: '🕌', title: 'Kuwait Towers', desc: 'Iconic towers on the Gulf coast are 30 min from the airport by taxi (~KWD 7 / $23). Good views of the Gulf. The Amiri Diwan palace area is also worth a visit.' },
      { icon: '🌡️', title: 'Severe summer heat', desc: 'Kuwait is one of the hottest countries on earth (up to 50°C in summer). Stick to air-conditioned spaces June–September.' },
      { icon: '🛍️', title: 'The Avenues Mall', desc: 'One of the largest malls in the Middle East — air-conditioned and a good snapshot of contemporary Kuwait. About 25 min from the airport.' },
      { icon: '🗣️', title: 'Language', desc: 'Arabic. Shukran (thanks), Min fadlak (please). English is widely spoken in Kuwait.' },
    ],
  },
  JNB: {
    airport: 'O.R. Tambo International Airport',
    city: 'Johannesburg',
    flag: '🇿🇦',
    lounges: 'South African Airways Masakhane Lounge (SA Business/Voyager Gold); SLOW Lounge (FNB Platinum/Priority Pass, T4)',
    tips: [
      { icon: '🚆', title: 'Gautrain to Sandton/Pretoria', desc: 'Gautrain from OR Tambo to Sandton in 15 min (ZAR 200 / ~$11), Pretoria 35 min (ZAR 190). Runs 5:30am–9:30pm weekdays.' },
      { icon: '🔒', title: 'Security awareness', desc: 'Johannesburg has a high crime rate. Use Gautrain or Uber (not metered taxis). Don\'t display phones or valuables. Stay in well-lit tourist zones.' },
      { icon: '🦁', title: 'Safari gateway', desc: 'JNB is the main gateway for Kruger National Park (6h drive) and many private reserves. Most visitors use Joburg purely as a transit hub.' },
      { icon: '🗣️', title: 'Language', desc: '11 official languages — English, Zulu, Xhosa, Afrikaans most common. Sawubona (Zulu hello), Dankie (Afrikaans thanks). English is the travel language throughout South Africa.' },
    ],
  },
  NBO: {
    airport: 'Jomo Kenyatta International Airport',
    city: 'Nairobi',
    flag: '🇰🇪',
    lounges: 'Kenya Airways Pride Lounge (KQ Business/Flying Blue Platinum); JamboJet Lounge (Priority Pass, T1A)',
    tips: [
      { icon: '🦒', title: 'Nairobi National Park', desc: 'The only national park in a capital city — lions, rhinos, and giraffes with skyscrapers as backdrop, 15 min from the airport. A 3h game drive with a guide runs ~$60. Truly unique.' },
      { icon: '🚕', title: 'Uber or airport taxis', desc: 'Uber works well in Nairobi and is significantly safer than street taxis. Bolt is also active. Use the official taxi stand at arrivals for metered taxis.' },
      { icon: '🍖', title: 'Nyama choma', desc: 'Kenyan roasted meat (nyama choma) — grilled goat or beef with ugali and sukuma wiki (braised greens). A genuine social food experience.' },
      { icon: '🗣️', title: 'Language', desc: 'Swahili and English. Asante sana (thank you very much), Karibu (welcome), Habari (how are you?). Both are official — English works everywhere in Nairobi.' },
    ],
  },
  ADD: {
    airport: 'Addis Ababa Bole International Airport',
    city: 'Addis Ababa',
    flag: '🇪🇹',
    lounges: 'Ethiopian Airlines Cloud Nine Lounge (ET Business/ShebaMiles Gold — excellent quality); Star Alliance Lounge (Priority Pass)',
    tips: [
      { icon: '🛫', title: 'Ethiopian Airlines hub', desc: 'ADD is the primary hub of Ethiopian Airlines — Africa\'s best carrier and a Star Alliance member. The Cloud Nine Business Lounge is excellent even by global standards.' },
      { icon: '☕', title: 'Coffee ceremony', desc: 'Ethiopia is the birthplace of coffee. The traditional ceremony (3 cups, 30–45 min) is offered in many local cafés — green beans roasted fresh in front of you.' },
      { icon: '🏛️', title: 'A surprising city', desc: 'Home to the African Union HQ, the vast Merkato market (largest in Africa), and excellent cuisine. At 2,355m altitude it\'s refreshingly cool despite being near the equator.' },
      { icon: '🗣️', title: 'Language', desc: 'Amharic (unique Ethiopian script). Ameseginalehu (formal thanks), Selam (hello). English is widely used in business and tourism.' },
    ],
  },
  CMN: {
    airport: 'Mohammed V International Airport',
    city: 'Casablanca',
    flag: '🇲🇦',
    lounges: 'Royal Air Maroc Safar Lounge (AT Business/Safar Gold); Casa Lounge (Priority Pass, Terminal 1)',
    tips: [
      { icon: '🚆', title: 'ONCF train to city (35 min)', desc: 'Train from the airport to Casa Voyageurs in 35 min, Casa Port in 45 min (MAD 48 / ~$5). Runs from early morning to midnight. Buy at the station just outside arrivals.' },
      { icon: '🕌', title: 'Hassan II Mosque', desc: 'One of the most magnificent mosques in the world — the 3rd largest, built over the Atlantic Ocean. Guided tours for non-Muslims run several times daily (~MAD 130). The coastal location is stunning.' },
      { icon: '🥘', title: 'Tagine and mint tea', desc: 'Moroccan cuisine is outstanding — slow-cooked tagines with preserved lemon, bastilla (pigeon pastry), and fresh orange juice everywhere. Mint tea is served sweet and ceremonially.' },
      { icon: '🗣️', title: 'Language', desc: 'Moroccan Arabic (Darija) and French. Merci/Shukran (thanks), Bonjour/Salam (hello). French works fluently in Casablanca — more so than Arabic in business contexts.' },
    ],
  },
  CPT: {
    airport: 'Cape Town International Airport',
    city: 'Cape Town',
    flag: '🇿🇦',
    lounges: 'South African Airways Lounge (SA Business/Voyager Gold); SLOW Lounge (FNB Platinum/Priority Pass)',
    tips: [
      { icon: '🚕', title: 'MyCiTi bus or Uber', desc: 'MyCiTi Bus Route 100 runs from the airport to the city every 20 min (ZAR 71 / ~$4, 30–50 min). Uber reliable at ~ZAR 150–200 to the Waterfront. Avoid unlicensed taxis.' },
      { icon: '🏔️', title: 'Table Mountain (3h+)', desc: 'Cable car to the flat-topped summit (closed in high winds) offers 360° views of the city, ocean, and Cape Peninsula. Book online to guarantee a spot.' },
      { icon: '🍷', title: 'Stellenbosch wine route', desc: 'Cape Town is surrounded by world-class wine country. Stellenbosch and Franschhoek are 45 min away — even a half-day wine tour is a highlight.' },
      { icon: '🗣️', title: 'Language', desc: 'Afrikaans, English, and Xhosa. Dankie (Afrikaans thanks), Enkosi (Xhosa thanks). English dominates in Cape Town.' },
    ],
  },
  LOS: {
    airport: 'Murtala Muhammed International Airport',
    city: 'Lagos',
    flag: '🇳🇬',
    lounges: 'Air Peace Lounge (P4 Business); Bi-Courtyard Lounge (Priority Pass, International Terminal)',
    tips: [
      { icon: '🚕', title: 'Use Uber only', desc: 'Always use Uber or Bolt from the airport — never hail unofficial taxis. Traffic in Lagos can be severe at any hour; allow 60–90 min to the city centre (Victoria Island or Lagos Island).' },
      { icon: '🌆', title: 'Most populous city in Africa', desc: 'Lagos is a pulsating megalopolis of 15M+ people — full of energy, music, and ambition. Victoria Island is the modern business hub; the Balogun Market in Lagos Island is overwhelming and wonderful.' },
      { icon: '🍲', title: 'Jollof rice is a religion', desc: 'Nigerian jollof rice (fried tomato-based rice) is one of the great dishes of West Africa. Pepper soup, suya (spiced grilled meat), and puff-puff (fried dough) are also essential.' },
      { icon: '🗣️', title: 'Language', desc: 'English (official), Yoruba, Hausa, Igbo. English is the language of business and education throughout Lagos. Locals are outgoing and conversational.' },
    ],
  },

  // ── Oceania ────────────────────────────────────────────────────────────────
  SYD: {
    airport: 'Sydney Kingsford Smith Airport',
    city: 'Sydney',
    flag: '🇦🇺',
    cityImage: 'photo-1506973035872-a4ec16b8e8d9',
    lounges: 'Qantas International Business Lounge T1 (QF Business/Gold); Singapore Airlines SilverKris Lounge T1 (SQ Business/PPS Club)',
    tips: [
      { icon: '🚆', title: 'Airport Link train (13 min)', desc: 'Train to Central Station every 10 min (AUD 21.20 incl. airport surcharge). Opal card saves a little. Uber to city ~AUD 40.' },
      { icon: '🌉', title: 'Sydney Harbour Bridge', desc: 'Circular Quay (2 stops from Central) has the Opera House, Harbour Bridge, and the Rocks historic district all within walking distance. The Manly Ferry (30 min) is spectacular.' },
      { icon: '🏄', title: 'Bondi Beach', desc: 'Train to Bondi Junction then 333 bus to Bondi Beach — 45 min total. The coastal walk from Bondi to Coogee is 6km of world-class coastal scenery.' },
      { icon: '🗣️', title: 'Language', desc: 'English with Australian slang. No ta (informal thanks), G\'day (hello). Australians are famously casual and friendly.' },
    ],
  },
  MEL: {
    airport: 'Melbourne Airport (Tullamarine)',
    city: 'Melbourne',
    flag: '🇦🇺',
    lounges: 'Qantas International Business Lounge T2 (QF Business/Gold); Emirates Lounge T2 (EK Business)',
    tips: [
      { icon: '🚌', title: 'Skybus to Southern Cross', desc: 'Skybus express coach to Southern Cross Station runs every 10 min, 24 hours (AUD 22.50, ~30 min off-peak). No direct train from Melbourne Airport.' },
      { icon: '☕', title: 'Coffee capital of the world', desc: 'Melbourne has a genuine claim to the world\'s best coffee culture — the laneways of the CBD are dense with exceptional independent cafés. Order a flat white.' },
      { icon: '🎨', title: 'Street art and laneways', desc: 'Hosier Lane and AC/DC Lane in the CBD are world-famous for street art. Federation Square hosts free cultural events almost daily.' },
      { icon: '🗣️', title: 'Language', desc: 'English with Australian slang. Melburnians are extremely proud of their city and always happy to give recommendations.' },
    ],
  },
  AKL: {
    airport: 'Auckland Airport',
    city: 'Auckland',
    flag: '🇳🇿',
    lounges: 'Air New Zealand International Lounge (NZ Business/Gold Elite); Qantas Business Lounge (QF Business/Gold)',
    tips: [
      { icon: '🚌', title: 'SkyBus to city (45 min)', desc: 'SkyBus runs 24h from the airport to the Sky Tower in the city centre (NZD 20 one-way). Taxis and Uber cost NZD 70–80. No direct rail link currently.' },
      { icon: '🌋', title: 'Volcano city', desc: 'Auckland sits on 53 volcanic cones — all dormant. Rangitoto Island and One Tree Hill (Maungakiekie) are the most dramatic. The Waitematā Harbour is stunning from the CBD waterfront.' },
      { icon: '🐑', title: 'Hobbiton (3h+)', desc: 'The actual Shire from Lord of the Rings is 2h south near Matamata. Tours run daily — even non-fans enjoy the rolling green New Zealand countryside.' },
      { icon: '🗣️', title: 'Language', desc: 'English and te reo Māori. Kia ora (hello/thank you), Haere mai (welcome). New Zealanders are famously warm. Basic Māori phrases are genuinely appreciated.' },
    ],
  },

  // ── North America (additional) ────────────────────────────────────────────
  YYZ: {
    airport: 'Toronto Pearson International Airport',
    city: 'Toronto',
    flag: '🇨🇦',
    lounges: 'Air Canada Maple Leaf Lounge T1 (AC Business/Super Elite); American Airlines Admirals Club T1 (AA Business)',
    tips: [
      { icon: '🚆', title: 'Union Pearson Express (25 min)', desc: 'UP Express runs non-stop to Union Station every 15 min (CAD 13.85, 25 min). Catches all major Toronto Transit connections. Much faster than taxis in traffic.' },
      { icon: '🏒', title: 'Hockey Hall of Fame', desc: 'Toronto is Canada\'s sports capital. The Hockey Hall of Fame at Brookfield Place is a genuine landmark. CN Tower was the world\'s tallest structure for 32 years.' },
      { icon: '🌊', title: 'Harbourfront and CN Tower', desc: 'The Harbourfront along Lake Ontario is free, scenic, and excellent for a long walk. Kensington Market is the most interesting neighbourhood.' },
      { icon: '🗣️', title: 'Language', desc: 'English and French. Toronto is one of the most multicultural cities in the world. Canadian politeness is genuine.' },
    ],
  },
  YVR: {
    airport: 'Vancouver International Airport',
    city: 'Vancouver',
    flag: '🇨🇦',
    lounges: 'Air Canada Maple Leaf Lounge International (AC Business/Super Elite); The Fairmont Vancouver Airport (hotel, day rooms available)',
    tips: [
      { icon: '🚇', title: 'Canada Line to downtown (25 min)', desc: 'SkyTrain Canada Line every 6–8 min to Waterfront Station (CAD 10.50 including airport surcharge). Runs ~5am–1am.' },
      { icon: '🏔️', title: 'Mountains right there', desc: 'Grouse Mountain is 45 min from downtown — hike or gondola. In winter, Whistler (2h drive) is world-class skiing. On clear days the Coastal Mountains are visible from the terminal.' },
      { icon: '🦀', title: 'Pacific seafood', desc: 'Wild salmon, Dungeness crab, spot prawns — Vancouver\'s food scene centers on the Pacific. Granville Island Market is the best food destination, 10 min from downtown.' },
      { icon: '🗣️', title: 'Language', desc: 'English (and a large Cantonese/Mandarin-speaking community). Mandarin is increasingly functional in Richmond near the airport.' },
    ],
  },
  SFO: {
    airport: 'San Francisco International Airport',
    city: 'San Francisco',
    flag: '🇺🇸',
    lounges: 'United Polaris Lounge T3 (UA Business/Global Services); Centurion Lounge (Amex Platinum, T3)',
    tips: [
      { icon: '🚇', title: 'BART to downtown (30 min)', desc: 'BART runs every 20 min from SFO International Terminal to Powell Street (Union Square) for $10.65. Avoid rideshare during rush hour — traffic can be brutal.' },
      { icon: '🌉', title: 'Golden Gate Bridge', desc: 'From downtown SF, Bus 28 or 29 goes to the bridge viewpoints for $3. Check marine layer forecasts — fog can obscure the view completely.' },
      { icon: '🦞', title: 'Boudin sourdough and clam chowder', desc: 'Boudin Bakery sourdough bread bowls with clam chowder at Fisherman\'s Wharf are an SF institution. The city\'s sourdough is uniquely tangy due to local wild yeast.' },
      { icon: '🗣️', title: 'Language', desc: 'English, with large Spanish and Chinese-speaking communities. Very internationally oriented.' },
    ],
  },
  SEA: {
    airport: 'Seattle-Tacoma International Airport',
    city: 'Seattle',
    flag: '🇺🇸',
    lounges: 'Alaska Airlines Board Room (AS MVP Gold/pay ~$60); Delta Sky Club (DL Platinum/Gold/pay)',
    tips: [
      { icon: '🚆', title: 'Link Light Rail (50 min)', desc: 'Link Light Rail every 8–15 min to downtown Seattle (Westlake Station) in 50 min for $3.25. One of the best airport-city rail connections in the US. Runs 5am–1am.' },
      { icon: '☕', title: 'Coffee capital of the US', desc: 'Seattle birthed Starbucks but is really a city of independent roasters — Victrola, Lighthouse, Caffe Vita. The original Starbucks at Pike Place Market is worth the photo.' },
      { icon: '🌲', title: 'Surrounded by mountains and water', desc: 'Mt Rainier is visible on clear days. Olympic National Park is 3h away. Even downtown has parks and water views.' },
      { icon: '🗣️', title: 'Language', desc: 'English, with a large East Asian community. Seattle is known for being polite and environmentally conscious.' },
    ],
  },
  BOS: {
    airport: 'Boston Logan International Airport',
    city: 'Boston',
    flag: '🇺🇸',
    lounges: 'Delta Sky Club T1 (DL Platinum/Gold/pay); American Admirals Club T1 (AA Business)',
    tips: [
      { icon: '🚇', title: 'Silver Line SL1 (free from T5)', desc: 'Free Silver Line SL1 bus from Logan terminals to South Station in 20 min. Connect to Red Line or commuter rail. Or take the water ferry from T1 pier to Rowes Wharf (~$5).' },
      { icon: '🏛️', title: 'Freedom Trail', desc: '4km self-guided walk through 16 Revolutionary-era sites — Paul Revere\'s house, Bunker Hill Monument. Start at Boston Common. All free, all within compact downtown.' },
      { icon: '🦞', title: 'Clam chowder and lobster rolls', desc: 'New England clam chowder (thick, creamy, potato) and lobster rolls are quintessential Boston. Legal Sea Foods in the airport terminal is a local institution.' },
      { icon: '🗣️', title: 'Language', desc: 'English with a distinctive Boston accent. Boston is full of universities — highly educated, internationally connected population.' },
    ],
  },
  EWR: {
    airport: 'Newark Liberty International Airport',
    city: 'New York',
    flag: '🇺🇸',
    lounges: 'United Polaris Lounge T-C (UA Business/Global Services); Centurion Lounge T-C (Amex Platinum)',
    tips: [
      { icon: '🚆', title: 'AirTrain + NJ Transit to NYC', desc: 'AirTrain to Newark Penn (free), then NJ Transit to NYC Penn in 33 min (~$16 total). Or Newark Airport Express bus to Port Authority (~$22, 45–60 min). Avoid taxis — $70–100+ to Manhattan.' },
      { icon: '🗽', title: 'Further than JFK but less crowded', desc: 'EWR is technically in New Jersey. Allow 60–90 min door-to-door to Midtown — more during peak hours.' },
      { icon: '🍕', title: 'New York pizza', desc: 'Joe\'s Pizza (West Village) and Di Fara (Brooklyn) are legendary. In the airport, grab a NY slice from any non-chain vendor in T-C. Fold in half, eat standing — that\'s correct form.' },
      { icon: '🗣️', title: 'Language', desc: 'English, with a huge Spanish-speaking community in Newark. New York City is the most linguistically diverse place on Earth.' },
    ],
  },
  IAH: {
    airport: 'George Bush Intercontinental Airport',
    city: 'Houston',
    flag: '🇺🇸',
    lounges: 'United Polaris Lounge T-C (UA Business/Global Services); United Club T-C/E (UA status/pay)',
    tips: [
      { icon: '🚌', title: 'Metro Bus to downtown', desc: 'IAH has no direct rail. Metro Bus 102 runs to Downtown Transit Center (~$1.25, 1h+). Uber/Lyft ~$35–55 to downtown (45 min). IAH is a long drive from the city centre.' },
      { icon: '🚀', title: 'Space Center Houston', desc: 'NASA\'s visitor center is 30 min from IAH — one of the best science museums in the US. The tram tour visits actual mission control rooms.' },
      { icon: '🥩', title: 'Texas BBQ', desc: 'Houston has excellent Texas BBQ. Brisket, ribs, and jalapeño sausage are non-negotiable. Killen\'s Barbecue (45 min) or Gatlin\'s BBQ near downtown.' },
      { icon: '🗣️', title: 'Language', desc: 'English, with the largest Hispanic population of any major US city. Spanish is widely spoken throughout Houston.' },
    ],
  },
  IAD: {
    airport: 'Washington Dulles International Airport',
    city: 'Washington D.C.',
    flag: '🇺🇸',
    lounges: 'United Club (UA status/pay); Air France Lounge (AF Business/Platinum); Lufthansa Lounge (LH Business/Senator)',
    tips: [
      { icon: '🚇', title: 'Silver Line Metro (60 min)', desc: 'Silver Line Express bus from Dulles connects to Wiehle-Reston East Metro station (Silver Line) to downtown DC in total ~60–70 min. Or Uber ~40–60 min depending on traffic on the Dulles Toll Road.' },
      { icon: '🏛️', title: 'Free Smithsonian museums', desc: 'The National Mall has 19 Smithsonian museums — all free. The National Air and Space Museum, Natural History, and American History are within walking distance of each other.' },
      { icon: '🌸', title: 'Cherry Blossoms (late March–early April)', desc: 'The National Mall cherry blossoms are world-famous. If your layover coincides, it is genuinely spectacular — especially around the Tidal Basin near the Jefferson Memorial.' },
      { icon: '🗣️', title: 'Language', desc: 'English. Washington DC has a very internationally diverse population — many languages are spoken throughout the city.' },
    ],
  },

  // ── Africa (additional) ───────────────────────────────────────────────────
  ACC: {
    airport: 'Kotoka International Airport',
    city: 'Accra',
    flag: '🇬🇭',
    lounges: 'Ghana Airways VIP Lounge (pay ~$25); Kotoka Business Lounge (Priority Pass, Terminal 3)',
    tips: [
      { icon: '🚕', title: 'Uber or official taxis', desc: 'Uber works well in Accra (~GHS 80–150 / $6–11 to city centre, 30–45 min depending on traffic). Indriver is also popular. Avoid unmarked taxis in arrivals — agree on fares before entering any unlicensed cab.' },
      { icon: '🏖️', title: 'Labadi Beach', desc: 'Labadi (La Pleasure Beach) is 20 min from the airport and the most popular beach in Ghana. Entry fee ~GHS 20. Lively on weekends with live highlife music and food stalls.' },
      { icon: '🍲', title: 'Jollof, waakye, and kelewele', desc: 'Ghanaian food is outstanding — jollof rice cooked in tomato broth, waakye (rice and beans), and kelewele (spiced fried plantain) are the staples. Chop bars (local restaurants) serve authentic and cheap meals.' },
      { icon: '🗣️', title: 'Language', desc: 'English (official) and Twi. Medaase (thanks in Twi), Akwaaba (welcome). Ghana has some of the highest English proficiency in West Africa — no issues navigating.' },
    ],
  },
  DSS: {
    airport: 'Blaise Diagne International Airport',
    city: 'Dakar',
    flag: '🇸🇳',
    lounges: 'Air Sénégal Business Lounge (HC Business); Salon VIP AIBD (pay ~$30)',
    tips: [
      { icon: '🚌', title: 'Bus or taxi to city', desc: 'DSS is 45 km from Dakar city centre. Express bus DDD runs to Dakar (1h, ~XOF 5,000 / $8). Taxis cost ~XOF 20,000–30,000 ($35–50). Negotiate fares firmly before entering any taxi.' },
      { icon: '🏝️', title: 'Gorée Island (UNESCO)', desc: 'The small island of Gorée — a haunting monument to the slave trade — is 20 min by ferry from Dakar port. The House of Slaves museum is one of the most important historical sites in Africa. Entry is free.' },
      { icon: '🐠', title: 'Thiéboudienne', desc: 'Senegal\'s national dish is thiéboudienne — rice cooked in tomato-fish broth with whole grilled fish and vegetables. One of the great dishes of West African cuisine. Eaten communally from a shared bowl.' },
      { icon: '🗣️', title: 'Language', desc: 'French (official) and Wolof. Merci (thanks), Déedéet (no in Wolof), Bonjour/Nanga def (hello). French is essential in Dakar — English is limited outside international hotels.' },
    ],
  },
  ABJ: {
    airport: 'Félix-Houphouët-Boigny International Airport',
    city: 'Abidjan',
    flag: '🇨🇮',
    lounges: 'Air Côte d\'Ivoire Business Lounge (HF Business); Salon VIP (Priority Pass, Terminal 1)',
    tips: [
      { icon: '🚕', title: 'Taxi or Yango', desc: 'Yango (ride-hailing) works well in Abidjan and is significantly safer than street taxis. Official taxis from arrivals are metered. The city is spread across a lagoon system — distances can be deceptive.' },
      { icon: '🌆', title: 'Plateau district', desc: 'Abidjan\'s Plateau district is the most modern CBD in West Africa — gleaming towers, wide boulevards, and the striking St Paul\'s Cathedral designed by Aldo Spirito. The Banco National Park (urban rainforest) is 30 min away.' },
      { icon: '🍛', title: 'Attiéké and aloco', desc: 'Ivorian cuisine centers on attiéké (fermented cassava couscous) served with grilled fish or chicken. Aloco (fried ripe plantain with chilli) is everywhere and addictive. A full meal at a maquis (local restaurant) costs XOF 2,000–4,000 ($3–6).' },
      { icon: '🗣️', title: 'Language', desc: 'French (official) and Dioula. Merci (thanks), Bonjour (hello). French is the only language needed throughout Abidjan — English is very limited.' },
    ],
  },
  TUN: {
    airport: 'Tunis-Carthage International Airport',
    city: 'Tunis',
    flag: '🇹🇳',
    lounges: 'Tunisair Business Lounge (TU Business); Carthage Lounge (Priority Pass, Terminal 1)',
    tips: [
      { icon: '🚇', title: 'Metro Léger to city', desc: 'Metro Léger (tram) from the airport to city centre takes ~30 min (TND 0.65 / ~$0.20 — remarkably cheap). Taxis run ~TND 10–15 ($3–5) to downtown. Much safer than unmarked cabs.' },
      { icon: '🏛️', title: 'Carthage ruins (2h+)', desc: 'The ancient Carthage archaeological site — Hannibal\'s city — is only 20 min from the airport by suburban train. The Bardo National Museum in Tunis holds the world\'s largest collection of Roman mosaics.' },
      { icon: '🥘', title: 'Brik and couscous', desc: 'Tunisian food is the most distinctive in North Africa — brik (crispy pastry filled with egg and tuna), harissa-spiced lamb couscous, and merguez sausage. Spicier and more Mediterranean than Moroccan cuisine.' },
      { icon: '🗣️', title: 'Language', desc: 'Tunisian Arabic and French. Merci/Shukran (thanks), Bonjour/Salam (hello). French is very widely understood throughout Tunisia — more so than in Morocco.' },
    ],
  },
  ALG: {
    airport: 'Houari Boumediene Airport',
    city: 'Algiers',
    flag: '🇩🇿',
    lounges: 'Air Algérie Business Lounge (AH Business); Salon Affaires (Priority Pass, Terminal 1)',
    tips: [
      { icon: '🚌', title: 'Bus or taxi to city', desc: 'Bus 34 runs from the airport to Grande Poste (city centre) in ~45 min (DZD 50 / ~$0.35). Taxis cost ~DZD 2,000–3,000 ($15–22). Negotiate before entering — meters are not always used.' },
      { icon: '🏙️', title: 'The Casbah of Algiers (UNESCO)', desc: 'The historic Casbah is a labyrinthine Ottoman-era medina on the hillside above the bay — UNESCO-listed and genuinely atmospheric. The Great Mosque of Algiers (Djamaa el Djazaïr) is one of the largest in the world.' },
      { icon: '🍢', title: 'Chorba and makroud', desc: 'Algerian soup (chorba) is thick, spiced, and warming. Makroud (semolina cookies filled with dates) are the classic sweet. Algerian cuisine blends Berber, Arab, Ottoman, and French influences.' },
      { icon: '🗣️', title: 'Language', desc: 'Algerian Arabic (Darja) and French. Merci/Shukran (thanks), Bonjour/Salam (hello). French is essential — widely used in business, education, and signage throughout Algiers.' },
    ],
  },
  EBB: {
    airport: 'Entebbe International Airport',
    city: 'Kampala',
    flag: '🇺🇬',
    lounges: 'Uganda Airlines Lounge (UR Business); Entebbe Lounge (Priority Pass, International Terminal)',
    tips: [
      { icon: '🚕', title: 'Taxi or special hire', desc: 'No rail link — use a special hire taxi from the official stand (UGX 80,000–120,000 / $22–32 to Kampala, 45–60 min). Negotiate beforehand. Bolt is expanding in Uganda but not yet at the airport.' },
      { icon: '🦍', title: 'Gorilla trekking gateway', desc: 'Entebbe is the main gateway for Bwindi Impenetrable Forest (mountain gorilla trekking) and Queen Elizabeth National Park. Permits sell out months in advance — book well ahead.' },
      { icon: '🌊', title: 'Lake Victoria', desc: 'The airport sits right on Lake Victoria — the world\'s largest tropical lake. The Entebbe Botanical Gardens on the lakeside are free and peaceful for a long layover.' },
      { icon: '🗣️', title: 'Language', desc: 'English (official) and Luganda. Thank you, Please — English works throughout Kampala. Webale (thanks in Luganda) is appreciated by locals.' },
    ],
  },
  DAR: {
    airport: 'Julius Nyerere International Airport',
    city: 'Dar es Salaam',
    flag: '🇹🇿',
    lounges: 'Precision Air Lounge (PW Business); KLM Crown Lounge (Priority Pass, International Terminal)',
    tips: [
      { icon: '🚕', title: 'Taxi from official stand', desc: 'Use taxis from the official stand inside arrivals (negotiate firmly, ~TZS 30,000–50,000 / $12–20 to city centre, 30–60 min). Bolt is now available in Dar and more reliable for pricing.' },
      { icon: '🏝️', title: 'Zanzibar gateway', desc: 'Most visitors use Dar as a connection to Zanzibar — a 25 min flight or 2h high-speed ferry from the port. Zanzibar\'s Stone Town (UNESCO) and white-sand beaches are among the best in Africa.' },
      { icon: '🍤', title: 'Seafood and Zanzibari spices', desc: 'Dar es Salaam has excellent coastal Swahili cuisine — grilled octopus, coconut fish curry, and mandazi (fried dough). The night food market at Kivukoni Front near the ferry terminal is outstanding.' },
      { icon: '🗣️', title: 'Language', desc: 'Swahili (Kiswahili) and English. Asante sana (thank you very much), Karibu (welcome), Habari (how are you?). Swahili is the most widely spoken African language — a few words go a long way.' },
    ],
  },
  KGL: {
    airport: 'Kigali International Airport',
    city: 'Kigali',
    flag: '🇷🇼',
    lounges: 'RwandAir Business Lounge (WB Business/Silverback); KLM/RwandAir Lounge (Priority Pass)',
    tips: [
      { icon: '🚕', title: 'Taxi or YegoMoto', desc: 'Official taxis from the airport run ~RWF 15,000–20,000 ($12–16) to city centre (20–30 min). Yego ride-hailing app is reliable and cheaper. The airport is remarkably close to the city.' },
      { icon: '🌿', title: 'Cleanest city in Africa', desc: 'Kigali is consistently ranked the cleanest, safest, and most well-governed city in Africa. Plastic bags are banned nationwide. The city is immaculately maintained and entirely walkable in the Nyarugenge district.' },
      { icon: '🦍', title: 'Gorilla trekking (2h from Kigali)', desc: 'Volcanoes National Park is 2–3h from Kigali by road — home to mountain gorillas. Permits are $1,500 but the experience is extraordinary. Book months in advance through Rwanda Development Board.' },
      { icon: '🗣️', title: 'Language', desc: 'Kinyarwanda, French, and English (all official). Murakoze (thanks), Muraho (hello). English has become dominant in business and education since 2008. Very easy to navigate.' },
    ],
  },
  LAD: {
    airport: 'Quatro de Fevereiro Airport',
    city: 'Luanda',
    flag: '🇦🇴',
    lounges: 'TAAG Angola Airlines Lounge (DT Business/Milhas Umbi); VIP Lounge (Priority Pass, International Terminal)',
    tips: [
      { icon: '🚕', title: 'Official taxis only', desc: 'Always use taxis from the official stand inside arrivals — Luanda has a high crime rate and unlicensed cabs are risky. Pre-booking through your hotel is safest. City centre is 4–8 km but traffic can make it 45–90 min.' },
      { icon: '💰', title: 'One of Africa\'s most expensive cities', desc: 'Luanda has been repeatedly ranked the most expensive city in the world for expats. A basic meal can cost $30–50. Budget significantly more than any other African city.' },
      { icon: '🏖️', title: 'Ilha do Cabo (Luanda Island)', desc: 'The narrow peninsula of Luanda Island is 30 min from the city — lined with seafood restaurants and beach clubs. Popular with expats and the Angolan middle class on weekends.' },
      { icon: '🗣️', title: 'Language', desc: 'Portuguese (official) and Kimbundu/Umbundu. Obrigado/Obrigada (thanks), Olá (hello). Angola is fully Lusophone — English is very limited outside international hotels and oil company offices.' },
    ],
  },
  MRU: {
    airport: 'Sir Seewoosagur Ramgoolam International Airport',
    city: 'Mauritius',
    flag: '🇲🇺',
    lounges: 'Air Mauritius Lounge (MK Business/Jade); Plaza Premium Lounge (Priority Pass, International Terminal)',
    tips: [
      { icon: '🚌', title: 'Bus or taxi to hotels', desc: 'Public buses are cheap (~MUR 35 / $0.75) but slow and infrequent from the airport. Taxis are metered — Grand Baie in the north is ~MUR 2,500 ($55), Port Louis ~MUR 1,200 ($27). Pre-booking through hotels is common.' },
      { icon: '🌺', title: 'Indian Ocean paradise', desc: 'Mauritius is one of the most beautiful islands in the world — turquoise lagoons, white beaches, lush interior mountains. The Black River Gorges National Park is free and has excellent hiking.' },
      { icon: '🍛', title: 'Creole and Mauritian cuisine', desc: 'Mauritian cuisine blends Indian, French, Chinese, and African influences — dholl puri (flatbread with lentils), gateau piment (chilli cakes), and the finest freshwater prawns anywhere. Street food is exceptional.' },
      { icon: '🗣️', title: 'Language', desc: 'Mauritian Creole, French, and English (all widely used). Merci (thanks), Bonjour (hello), Thank you. Mauritius is the easiest African island to navigate — all three languages work.' },
    ],
  },
  MPM: {
    airport: 'Maputo International Airport',
    city: 'Maputo',
    flag: '🇲🇿',
    lounges: 'LAM Mozambique Business Lounge (TM Business); VIP Lounge (Priority Pass)',
    tips: [
      { icon: '🚕', title: 'Taxi from official stand', desc: 'Official taxis from the arrivals hall run ~MZN 500–800 ($8–13) to the city centre (15–20 min). Uber is active in Maputo. Agree on fares in advance with metered taxis.' },
      { icon: '🦞', title: 'Best prawns in the world', desc: 'Maputo\'s Piri Piri prawns (camarão grelhado) are a genuine world wonder — enormous, grilled over charcoal with garlic and lemon. Restaurante Costa do Sol overlooking the bay is the legendary spot, open since 1938.' },
      { icon: '🎨', title: 'Vibrant arts scene', desc: 'Mozambique has one of Africa\'s most distinct artistic traditions. The Natural History Museum has a famous whale skeleton exhibit. The baixa (downtown) has colonial Portuguese architecture and excellent cafés.' },
      { icon: '🗣️', title: 'Language', desc: 'Portuguese (official) and Changana/Ndau. Obrigado/Obrigada (thanks), Olá (hello). Portuguese is essential throughout Mozambique — English is limited outside Maputo hotels.' },
    ],
  },
  LUN: {
    airport: 'Kenneth Kaunda International Airport',
    city: 'Lusaka',
    flag: '🇿🇲',
    lounges: 'Zambia Airways Lounge (Q3 Business); Bwana Lounge (Priority Pass, International Terminal)',
    tips: [
      { icon: '🚕', title: 'Taxi or Yango', desc: 'Yango and inDrive are the most reliable ride-hailing options in Lusaka (~ZMW 120–180 / $6–9 to city centre, 20–30 min). Official taxis from the arrivals hall are also legitimate.' },
      { icon: '💧', title: 'Victoria Falls gateway', desc: 'Lusaka connects to Livingstone and Victoria Falls — one of the Seven Natural Wonders of the World — by a 1h domestic flight or 7h bus. The Falls are on the Zambia-Zimbabwe border and best seen from both sides.' },
      { icon: '🐘', title: 'South Luangwa National Park', desc: 'Widely considered one of the best game parks in Africa for walking safaris — a genuine alternative to Kenya/Tanzania. 6h drive from Lusaka, or a short domestic flight to Mfuwe airport.' },
      { icon: '🗣️', title: 'Language', desc: 'English (official) and Bemba/Nyanja. Thank you, Please — English is fully functional throughout Lusaka. Zikomo (thanks in Nyanja) is appreciated by locals.' },
    ],
  },

  // ── Latin America ─────────────────────────────────────────────────────────
  CUN: {
    airport: 'Cancún International Airport',
    city: 'Cancún',
    flag: '🇲🇽',
    lounges: 'VIP Lounge Terminal 3 (Priority Pass, pay ~$35); Sala VIP Terminal 4 (Priority Pass)',
    tips: [
      { icon: '🏖️', title: 'Hotel Zone or city', desc: 'ADO bus from the airport to the Hotel Zone runs ~every 30 min (~$3). Taxi to the Hotel Zone is ~$35 fixed rate. Most visitors head straight to resorts.' },
      { icon: '🌊', title: 'Cenotes are unmissable', desc: 'The Yucatán Peninsula has thousands of underground freshwater pools. Ik-Kil near Chichén Itzá, Gran Cenote near Tulum, Dos Ojos — world-class. Book tours from any hotel desk.' },
      { icon: '🏛️', title: 'Chichén Itzá (3h+)', desc: 'One of the Seven Wonders of the World — 2h drive from Cancún. Go early morning before the heat and crowds. Combine with a cenote visit.' },
      { icon: '🗣️', title: 'Language', desc: 'Spanish. Gracias (thanks), Por favor (please), Hola (hi). English is very widely spoken throughout the Cancún tourist corridor.' },
    ],
  },
};

// Minimum layover minutes to show airport guide
export const LAYOVER_GUIDE_THRESHOLD_MIN = 120; // 2 hours

export function getLayoverGuide(airportCode: string): LayoverGuide | null {
  return GUIDES[airportCode.toUpperCase()] ?? null;
}

export function parseLayoverMinutes(layoverStr: string): number {
  // layoverStr format: "2h 30m" or "5h" or "45m"
  const hMatch = layoverStr.match(/(\d+)h/);
  const mMatch = layoverStr.match(/(\d+)m/);
  const h = hMatch ? parseInt(hMatch[1]) : 0;
  const m = mMatch ? parseInt(mMatch[1]) : 0;
  return h * 60 + m;
}
