export type VisaRequirement = 'visa_free' | 'visa_on_arrival' | 'e_visa' | 'embassy_visa' | 'entry_restricted';

export interface PreEntryForm {
  name: string;
  deadline: string;
  url: string;
}

export interface VisaEntry {
  requirement: VisaRequirement;
  duration?: string;
  notes?: string;
  vaccinations?: string[];
  preEntryForms?: PreEntryForm[];
}

export interface Country {
  code: string;
  name: string;
}

export function flagEmoji(code: string): string {
  const a = code.toUpperCase().charCodeAt(0) - 65 + 0x1F1E6;
  const b = code.toUpperCase().charCodeAt(1) - 65 + 0x1F1E6;
  return String.fromCodePoint(a) + String.fromCodePoint(b);
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BR', name: 'Brazil' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'EE', name: 'Estonia' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GR', name: 'Greece' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MX', name: 'Mexico' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syria' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
];

// Maps lowercase city/country name keywords → ISO country code
export const CITY_TO_COUNTRY: Record<string, string> = {
  // Southeast Asia
  'bangkok': 'TH', 'chiang mai': 'TH', 'phuket': 'TH', 'koh samui': 'TH',
  'krabi': 'TH', 'koh phi phi': 'TH', 'thailand': 'TH',
  'bali': 'ID', 'jakarta': 'ID', 'lombok': 'ID', 'yogyakarta': 'ID', 'indonesia': 'ID',
  'singapore': 'SG',
  'kuala lumpur': 'MY', 'penang': 'MY', 'langkawi': 'MY', 'malaysia': 'MY',
  'ho chi minh': 'VN', 'saigon': 'VN', 'hanoi': 'VN', 'hoi an': 'VN',
  'da nang': 'VN', 'vietnam': 'VN', 'hcmc': 'VN',
  'phnom penh': 'KH', 'siem reap': 'KH', 'cambodia': 'KH',
  'manila': 'PH', 'cebu': 'PH', 'boracay': 'PH', 'philippines': 'PH',
  'yangon': 'MM', 'mandalay': 'MM', 'myanmar': 'MM', 'burma': 'MM',
  'vientiane': 'LA', 'luang prabang': 'LA', 'laos': 'LA',
  // East Asia
  'tokyo': 'JP', 'osaka': 'JP', 'kyoto': 'JP', 'hiroshima': 'JP',
  'sapporo': 'JP', 'japan': 'JP',
  'seoul': 'KR', 'busan': 'KR', 'korea': 'KR', 'south korea': 'KR',
  'hong kong': 'HK',
  'taipei': 'TW', 'taiwan': 'TW',
  'beijing': 'CN', 'shanghai': 'CN', 'china': 'CN', 'guangzhou': 'CN',
  // South Asia
  'delhi': 'IN', 'mumbai': 'IN', 'goa': 'IN', 'jaipur': 'IN',
  'india': 'IN', 'bengaluru': 'IN', 'bangalore': 'IN',
  'kathmandu': 'NP', 'nepal': 'NP',
  'colombo': 'LK', 'sri lanka': 'LK',
  'dhaka': 'BD', 'bangladesh': 'BD',
  // Indian Ocean
  'male': 'MV', 'maldives': 'MV',
  // Middle East
  'dubai': 'AE', 'abu dhabi': 'AE', 'uae': 'AE', 'united arab emirates': 'AE',
  'doha': 'QA', 'qatar': 'QA',
  'riyadh': 'SA', 'jeddah': 'SA', 'saudi arabia': 'SA',
  'amman': 'JO', 'petra': 'JO', 'jordan': 'JO',
  'tel aviv': 'IL', 'jerusalem': 'IL', 'israel': 'IL',
  'beirut': 'LB', 'lebanon': 'LB',
  'istanbul': 'TR', 'ankara': 'TR', 'turkey': 'TR',
  'muscat': 'OM', 'oman': 'OM',
  // Europe
  'paris': 'FR', 'nice': 'FR', 'lyon': 'FR', 'france': 'FR',
  'london': 'GB', 'manchester': 'GB', 'edinburgh': 'GB',
  'england': 'GB', 'uk': 'GB', 'united kingdom': 'GB', 'britain': 'GB',
  'rome': 'IT', 'milan': 'IT', 'venice': 'IT', 'florence': 'IT', 'italy': 'IT',
  'barcelona': 'ES', 'madrid': 'ES', 'seville': 'ES', 'spain': 'ES',
  'amsterdam': 'NL', 'netherlands': 'NL', 'holland': 'NL',
  'berlin': 'DE', 'munich': 'DE', 'hamburg': 'DE', 'germany': 'DE',
  'lisbon': 'PT', 'porto': 'PT', 'portugal': 'PT',
  'athens': 'GR', 'santorini': 'GR', 'mykonos': 'GR', 'greece': 'GR',
  'vienna': 'AT', 'austria': 'AT',
  'prague': 'CZ', 'czech republic': 'CZ', 'czechia': 'CZ',
  'budapest': 'HU', 'hungary': 'HU',
  'warsaw': 'PL', 'krakow': 'PL', 'poland': 'PL',
  'dubai city': 'AE',
  'zurich': 'CH', 'geneva': 'CH', 'switzerland': 'CH',
  'stockholm': 'SE', 'sweden': 'SE',
  'oslo': 'NO', 'norway': 'NO',
  'copenhagen': 'DK', 'denmark': 'DK',
  'helsinki': 'FI', 'finland': 'FI',
  'brussels': 'BE', 'belgium': 'BE',
  'dubrovnik': 'HR', 'croatia': 'HR',
  'reykjavik': 'IS', 'iceland': 'IS',
  // Africa
  'cairo': 'EG', 'luxor': 'EG', 'egypt': 'EG',
  'marrakech': 'MA', 'casablanca': 'MA', 'fez': 'MA', 'morocco': 'MA',
  'johannesburg': 'ZA', 'cape town': 'ZA', 'durban': 'ZA', 'south africa': 'ZA',
  'nairobi': 'KE', 'mombasa': 'KE', 'kenya': 'KE',
  'zanzibar': 'TZ', 'dar es salaam': 'TZ', 'tanzania': 'TZ',
  'addis ababa': 'ET', 'ethiopia': 'ET',
  'accra': 'GH', 'ghana': 'GH',
  'lagos': 'NG', 'abuja': 'NG', 'nigeria': 'NG',
  'tunis': 'TN', 'tunisia': 'TN',
  // Americas
  'new york': 'US', 'los angeles': 'US', 'miami': 'US', 'las vegas': 'US',
  'san francisco': 'US', 'chicago': 'US', 'usa': 'US', 'united states': 'US',
  'cancun': 'MX', 'mexico city': 'MX', 'playa del carmen': 'MX',
  'tulum': 'MX', 'cabo': 'MX', 'mexico': 'MX',
  'rio de janeiro': 'BR', 'sao paulo': 'BR', 'brazil': 'BR', 'salvador': 'BR',
  'bogota': 'CO', 'cartagena': 'CO', 'medellin': 'CO', 'colombia': 'CO',
  'buenos aires': 'AR', 'argentina': 'AR',
  'lima': 'PE', 'cusco': 'PE', 'machu picchu': 'PE', 'peru': 'PE',
  'toronto': 'CA', 'vancouver': 'CA', 'montreal': 'CA', 'canada': 'CA',
  // Oceania
  'sydney': 'AU', 'melbourne': 'AU', 'brisbane': 'AU', 'cairns': 'AU', 'australia': 'AU',
  'auckland': 'NZ', 'queenstown': 'NZ', 'new zealand': 'NZ',
};

// Key: `${passportISO}-${destinationISO}`
export const VISA_DATA: Record<string, VisaEntry> = {
  // ── US passport ──────────────────────────────────────────────────────
  'US-TH': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival. Extension to 30 more days possible at immigration office.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'Thailand Digital Arrival Card (TDAC)', deadline: 'Within 72 hours before arrival', url: 'https://tdac.immigration.go.th' }] },
  'US-ID': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival (Bali, Jakarta). Extension to 60 days available at immigration.' },
  'US-JP': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required. Register for Visit Japan Web for faster clearance.' },
  'US-SG': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'US-MY': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'US-AE': { requirement: 'visa_free', duration: '30 days', notes: 'Visa on arrival issued at the airport, free of charge. Extendable.' },
  'US-VN': { requirement: 'visa_free', duration: '45 days', notes: 'Visa-free since Aug 2023. E-visa available for up to 90 days ($25).' },
  'US-KH': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $30 at major airports, or e-visa online at evisa.gov.kh ($36).' },
  'US-PH': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required. Extensions available at Bureau of Immigration.' },
  'US-LA': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival at major entry points (~$35).' },
  'US-MM': { requirement: 'e_visa', duration: '28 days', notes: 'e-Visa required. Apply online at evisa.moip.gov.mm (~$50). Single entry.' },
  'US-IN': { requirement: 'e_visa', duration: '60 days', notes: 'e-Visa required. Apply at indianvisaonline.gov.in. Multiple entries available.' },
  'US-NP': { requirement: 'visa_on_arrival', duration: '15–90 days', notes: 'Visa on arrival at Tribhuvan Airport. 15 days $30, 30 days $50, 90 days $125.' },
  'US-LK': { requirement: 'e_visa', duration: '30 days', notes: 'ETA required at eta.gov.lk ($35). Apply before travel.' },
  'US-TR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required for up to 90 days in any 180-day period.' },
  'US-EG': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival at airport ($25), or e-visa online at visa2egypt.gov.eg.' },
  'US-MA': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'US-ZA': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'US-KE': { requirement: 'e_visa', duration: '90 days', notes: 'e-Visa required. Apply at evisa.go.ke ($51 single, $101 multiple entry).' },
  'US-TZ': { requirement: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival ($50 single) or online e-visa.' },
  'US-MX': { requirement: 'visa_free', duration: '180 days', notes: 'No visa required. FMM tourist card issued on arrival (often included in airfare).' },
  'US-BR': { requirement: 'visa_free', duration: '90 days', notes: 'Visa-free since 2024.', vaccinations: ['yellow_fever'] },
  'US-CO': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'CheckMig', deadline: 'Within 72 hours before arrival', url: 'https://apps.migracioncolombia.gov.co/pre-registro' }] },
  'US-PE': { requirement: 'visa_free', duration: '183 days', notes: 'No visa required.' },
  'US-AR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'US-FR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in any 180-day Schengen period.' },
  'US-IT': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in any 180-day Schengen period.' },
  'US-ES': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in any 180-day Schengen period.' },
  'US-DE': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in any 180-day Schengen period.' },
  'US-PT': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in any 180-day Schengen period.' },
  'US-GR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in any 180-day Schengen period.' },
  'US-NL': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in any 180-day Schengen period.' },
  'US-GB': { requirement: 'visa_free', duration: '6 months', notes: 'No visa required for up to 6 months.' },
  'US-AU': { requirement: 'e_visa', duration: '12 months', notes: 'eTA (Electronic Travel Authority) required. Apply online at immi.homeaffairs.gov.au (AUD$20, usually instant).' },
  'US-NZ': { requirement: 'e_visa', duration: '90 days', notes: 'NZeTA required. Apply in the NZeTA app or online (NZD$23). Usually instant approval.' },
  'US-MV': { requirement: 'visa_free', duration: '30 days', notes: 'Free 30-day on-arrival visa stamp. Extendable.' },
  'US-CN': { requirement: 'visa_free', duration: '15 days', notes: '15-day visa-free for US passport holders (2024 policy). Embassy visa required for longer stays.' },
  'US-KR': { requirement: 'visa_free', duration: '90 days', notes: 'K-ETA (electronic travel authorization) required. Free at k-eta.go.kr.' },
  'US-HK': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'US-TW': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'US-JO': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival (JD40, ~$56). Jordan Pass includes visa fee if you visit Petra.' },
  'US-QA': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'US-CA': { requirement: 'visa_free', duration: 'No limit', notes: 'No visa required for US citizens entering Canada.' },

  // ── UK passport ──────────────────────────────────────────────────────
  'GB-TH': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'Thailand Digital Arrival Card (TDAC)', deadline: 'Within 72 hours before arrival', url: 'https://tdac.immigration.go.th' }] },
  'GB-ID': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'GB-JP': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'GB-SG': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'GB-MY': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'GB-AE': { requirement: 'visa_free', duration: '30 days', notes: 'Free visa on arrival.' },
  'GB-VN': { requirement: 'visa_free', duration: '45 days', notes: 'Visa-free since Aug 2023.' },
  'GB-KH': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $30 or e-visa $36.' },
  'GB-IN': { requirement: 'e_visa', duration: '60 days', notes: 'e-Visa required. Apply at indianvisaonline.gov.in.' },
  'GB-AU': { requirement: 'e_visa', duration: '12 months', notes: 'eTA required (AUD$20). Apply online.' },
  'GB-NZ': { requirement: 'visa_free', duration: '6 months', notes: 'No visa required.' },
  'GB-US': { requirement: 'e_visa', duration: '90 days', notes: 'ESTA required ($21). Apply at esta.cbp.dhs.gov before travel.' },
  'GB-CN': { requirement: 'visa_free', duration: '15 days', notes: '15-day visa-free for UK passport holders (2024 policy).' },
  'GB-BR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'] },
  'GB-CO': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'CheckMig', deadline: 'Within 72 hours before arrival', url: 'https://apps.migracioncolombia.gov.co/pre-registro' }] },
  'GB-TR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'GB-EG': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $25 or e-visa.' },
  'GB-ZA': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'GB-MV': { requirement: 'visa_free', duration: '30 days', notes: 'Free on arrival.' },
  'GB-MX': { requirement: 'visa_free', duration: '180 days', notes: 'No visa required.' },
  'GB-KR': { requirement: 'visa_free', duration: '90 days', notes: 'K-ETA required (free).' },
  'GB-HK': { requirement: 'visa_free', duration: '6 months', notes: 'No visa required.' },
  'GB-TW': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'GB-MA': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'GB-KE': { requirement: 'e_visa', duration: '90 days', notes: 'e-Visa required at evisa.go.ke.' },
  'GB-QA': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'GB-CA': { requirement: 'e_visa', duration: '6 months', notes: 'eTA required ($7 CAD). Apply at canada.ca/en/immigration-refugees-citizenship.' },
  'GB-LA': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival (~$35).' },
  'GB-MM': { requirement: 'e_visa', duration: '28 days', notes: 'e-Visa required.' },
  'GB-NP': { requirement: 'visa_on_arrival', duration: '15–90 days', notes: 'Visa on arrival. 15 days $30, 30 days $50, 90 days $125.' },

  // ── Australian passport ───────────────────────────────────────────────
  'AU-TH': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'Thailand Digital Arrival Card (TDAC)', deadline: 'Within 72 hours before arrival', url: 'https://tdac.immigration.go.th' }] },
  'AU-ID': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'AU-JP': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'AU-SG': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'AU-MY': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'AU-AE': { requirement: 'visa_free', duration: '30 days', notes: 'Free visa on arrival.' },
  'AU-VN': { requirement: 'visa_free', duration: '45 days', notes: 'Visa-free since Aug 2023.' },
  'AU-IN': { requirement: 'e_visa', duration: '60 days', notes: 'e-Visa required. Apply online.' },
  'AU-US': { requirement: 'e_visa', duration: '90 days', notes: 'ESTA required ($21). Apply at esta.cbp.dhs.gov.' },
  'AU-GB': { requirement: 'visa_free', duration: '6 months', notes: 'No visa required.' },
  'AU-NZ': { requirement: 'visa_free', duration: 'Indefinite', notes: 'No visa required. NZ citizens have special travel rights.' },
  'AU-KH': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $30 or e-visa $36.' },
  'AU-BR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'] },
  'AU-CO': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'CheckMig', deadline: 'Within 72 hours before arrival', url: 'https://apps.migracioncolombia.gov.co/pre-registro' }] },
  'AU-CN': { requirement: 'visa_free', duration: '15 days', notes: '15-day visa-free (2024 policy).' },
  'AU-ZA': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'AU-MV': { requirement: 'visa_free', duration: '30 days', notes: 'Free on arrival.' },
  'AU-TR': { requirement: 'e_visa', duration: '90 days', notes: 'e-Visa required at evisa.gov.tr (approx $20).' },
  'AU-EG': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $25 or e-visa.' },
  'AU-KR': { requirement: 'visa_free', duration: '90 days', notes: 'K-ETA required (free).' },
  'AU-HK': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'AU-TW': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'AU-MA': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'AU-MX': { requirement: 'visa_free', duration: '180 days', notes: 'No visa required.' },
  'AU-LA': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival (~$35).' },
  'AU-MM': { requirement: 'e_visa', duration: '28 days', notes: 'e-Visa required.' },
  'AU-NP': { requirement: 'visa_on_arrival', duration: '15–90 days', notes: 'Visa on arrival at Tribhuvan Airport.' },
  'AU-KE': { requirement: 'e_visa', duration: '90 days', notes: 'e-Visa required at evisa.go.ke.' },

  // ── Canadian passport ─────────────────────────────────────────────────
  'CA-TH': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'Thailand Digital Arrival Card (TDAC)', deadline: 'Within 72 hours before arrival', url: 'https://tdac.immigration.go.th' }] },
  'CA-ID': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'CA-JP': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'CA-SG': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'CA-MY': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'CA-AE': { requirement: 'visa_free', duration: '30 days', notes: 'Free visa on arrival.' },
  'CA-VN': { requirement: 'visa_free', duration: '45 days', notes: 'Visa-free since Aug 2023.' },
  'CA-IN': { requirement: 'e_visa', duration: '60 days', notes: 'e-Visa required. Apply online.' },
  'CA-US': { requirement: 'visa_free', duration: 'No limit', notes: 'No visa required for Canadian citizens.' },
  'CA-GB': { requirement: 'e_visa', duration: '6 months', notes: 'ETA required for flying into UK (£10). Apply at gov.uk/electronic-travel-authorisation.' },
  'CA-AU': { requirement: 'e_visa', duration: '12 months', notes: 'eTA required (AUD$20).' },
  'CA-NZ': { requirement: 'visa_free', duration: '6 months', notes: 'No visa required.' },
  'CA-BR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'] },
  'CA-CO': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'CheckMig', deadline: 'Within 72 hours before arrival', url: 'https://apps.migracioncolombia.gov.co/pre-registro' }] },
  'CA-MX': { requirement: 'visa_free', duration: '180 days', notes: 'No visa required.' },
  'CA-KH': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $30 or e-visa $36.' },
  'CA-CN': { requirement: 'visa_free', duration: '15 days', notes: '15-day visa-free (2024 policy).' },
  'CA-ZA': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'CA-TR': { requirement: 'e_visa', duration: '90 days', notes: 'e-Visa required at evisa.gov.tr.' },
  'CA-EG': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $25 or e-visa.' },
  'CA-KR': { requirement: 'visa_free', duration: '90 days', notes: 'K-ETA required (free).' },
  'CA-MV': { requirement: 'visa_free', duration: '30 days', notes: 'Free on arrival.' },
  'CA-MA': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'CA-FR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in Schengen area.' },
  'CA-IT': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in Schengen area.' },
  'CA-LA': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival (~$35).' },
  'CA-NP': { requirement: 'visa_on_arrival', duration: '15–90 days', notes: 'Visa on arrival at Tribhuvan Airport.' },
  'CA-KE': { requirement: 'e_visa', duration: '90 days', notes: 'e-Visa required at evisa.go.ke.' },

  // ── Israeli passport ──────────────────────────────────────────────────
  'IL-TH': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'Thailand Digital Arrival Card (TDAC)', deadline: 'Within 72 hours before arrival', url: 'https://tdac.immigration.go.th' }] },
  'IL-ID': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'IL-JP': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'IL-SG': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'IL-MY': { requirement: 'entry_restricted', notes: 'Israeli passport holders are NOT permitted to enter Malaysia. This is an official restriction — plan an alternative route.' },
  'IL-AE': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free since normalization of relations in 2020 (Abraham Accords).' },
  'IL-VN': { requirement: 'visa_free', duration: '15 days', notes: '15 days visa-free. E-visa available for up to 90 days ($25).' },
  'IL-KH': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $30 or e-visa.' },
  'IL-IN': { requirement: 'e_visa', duration: '60 days', notes: 'e-Visa required.' },
  'IL-TR': { requirement: 'e_visa', duration: '90 days', notes: 'e-Visa required at evisa.gov.tr.' },
  'IL-EG': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $25 (peace treaty). Sinai-only permit also available.' },
  'IL-JO': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival available (peace treaty). Jordan Pass includes visa fee.' },
  'IL-US': { requirement: 'e_visa', duration: '90 days', notes: 'ESTA required ($21). Israel joined the Visa Waiver Program in 2023.' },
  'IL-GB': { requirement: 'visa_free', duration: '6 months', notes: 'No visa required.' },
  'IL-AU': { requirement: 'e_visa', duration: '12 months', notes: 'eTA required (AUD$20).' },
  'IL-BR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'] },
  'IL-CO': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'], preEntryForms: [{ name: 'CheckMig', deadline: 'Within 72 hours before arrival', url: 'https://apps.migracioncolombia.gov.co/pre-registro' }] },
  'IL-FR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in Schengen area.' },
  'IL-DE': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in Schengen area.' },
  'IL-IT': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in Schengen area.' },
  'IL-ES': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in Schengen area.' },
  'IL-GR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in Schengen area.' },
  'IL-CN': { requirement: 'embassy_visa', duration: 'Varies', notes: 'Visa required. Apply at Chinese embassy.' },
  'IL-ZA': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'IL-MV': { requirement: 'visa_free', duration: '30 days', notes: 'Free on arrival.' },
  'IL-MX': { requirement: 'visa_free', duration: '180 days', notes: 'No visa required.' },
  'IL-MA': { requirement: 'visa_free', duration: '90 days', notes: 'Morocco–Israel relations restored 2020. Visa-free.' },
  'IL-NP': { requirement: 'visa_on_arrival', duration: '15–90 days', notes: 'Visa on arrival at Tribhuvan Airport.' },
  'IL-LA': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival (~$35).' },

  // ── German passport ───────────────────────────────────────────────────
  'DE-TH': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'DE-ID': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'DE-JP': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'DE-SG': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'DE-MY': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'DE-AE': { requirement: 'visa_free', duration: '30 days', notes: 'Free visa on arrival.' },
  'DE-VN': { requirement: 'visa_free', duration: '45 days', notes: 'Visa-free since Aug 2023.' },
  'DE-US': { requirement: 'e_visa', duration: '90 days', notes: 'ESTA required ($21). Apply at esta.cbp.dhs.gov.' },
  'DE-AU': { requirement: 'e_visa', duration: '12 months', notes: 'eTA required (AUD$20).' },
  'DE-IN': { requirement: 'e_visa', duration: '60 days', notes: 'e-Visa required.' },
  'DE-CN': { requirement: 'visa_free', duration: '15 days', notes: '15-day visa-free (2024 policy).' },
  'DE-BR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'DE-CO': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'] },
  'DE-ZA': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'DE-TR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'DE-MX': { requirement: 'visa_free', duration: '180 days', notes: 'No visa required.' },
  'DE-KH': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $30 or e-visa.' },
  'DE-MV': { requirement: 'visa_free', duration: '30 days', notes: 'Free on arrival.' },
  'DE-KR': { requirement: 'visa_free', duration: '90 days', notes: 'K-ETA required (free).' },
  'DE-GB': { requirement: 'e_visa', duration: '6 months', notes: 'ETA required for UK entry (£10).' },

  // ── French passport ───────────────────────────────────────────────────
  'FR-TH': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'FR-ID': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'FR-JP': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'FR-AE': { requirement: 'visa_free', duration: '30 days', notes: 'Free visa on arrival.' },
  'FR-VN': { requirement: 'visa_free', duration: '45 days', notes: 'Visa-free since Aug 2023.' },
  'FR-US': { requirement: 'e_visa', duration: '90 days', notes: 'ESTA required ($21).' },
  'FR-AU': { requirement: 'e_visa', duration: '12 months', notes: 'eTA required (AUD$20).' },
  'FR-IN': { requirement: 'e_visa', duration: '60 days', notes: 'e-Visa required.' },
  'FR-CN': { requirement: 'visa_free', duration: '15 days', notes: '15-day visa-free (2024 policy).' },
  'FR-MA': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'FR-CO': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'] },
  'FR-BR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'FR-ZA': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'FR-MX': { requirement: 'visa_free', duration: '180 days', notes: 'No visa required.' },
  'FR-GB': { requirement: 'e_visa', duration: '6 months', notes: 'ETA required for UK entry (£10).' },
  'FR-TR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'FR-KH': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $30 or e-visa.' },
  'FR-MV': { requirement: 'visa_free', duration: '30 days', notes: 'Free on arrival.' },

  // ── New Zealand passport ──────────────────────────────────────────────
  'NZ-TH': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'NZ-ID': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'NZ-JP': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'NZ-SG': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'NZ-AE': { requirement: 'visa_free', duration: '30 days', notes: 'Free visa on arrival.' },
  'NZ-US': { requirement: 'e_visa', duration: '90 days', notes: 'ESTA required ($21).' },
  'NZ-AU': { requirement: 'visa_free', duration: 'Indefinite', notes: 'No visa required. Special Category Visa on arrival.' },
  'NZ-IN': { requirement: 'e_visa', duration: '60 days', notes: 'e-Visa required.' },
  'NZ-VN': { requirement: 'visa_free', duration: '45 days', notes: 'Visa-free.' },
  'NZ-CO': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.', vaccinations: ['yellow_fever'] },
  'NZ-CN': { requirement: 'visa_free', duration: '15 days', notes: '15-day visa-free (2024 policy).' },
  'NZ-GB': { requirement: 'visa_free', duration: '6 months', notes: 'No visa required.' },
  'NZ-KR': { requirement: 'visa_free', duration: '90 days', notes: 'K-ETA required (free).' },
  'NZ-MV': { requirement: 'visa_free', duration: '30 days', notes: 'Free on arrival.' },
  'NZ-MA': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'NZ-MX': { requirement: 'visa_free', duration: '180 days', notes: 'No visa required.' },
  'NZ-KH': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $30 or e-visa.' },

  // ── Singapore passport ────────────────────────────────────────────────
  'SG-TH': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'SG-ID': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free on arrival.' },
  'SG-JP': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'SG-MY': { requirement: 'visa_free', duration: '90 days', notes: 'No visa required.' },
  'SG-AE': { requirement: 'visa_free', duration: '30 days', notes: 'Free visa on arrival.' },
  'SG-VN': { requirement: 'visa_free', duration: '30 days', notes: 'Visa-free.' },
  'SG-KH': { requirement: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival $30 or e-visa.' },
  'SG-IN': { requirement: 'e_visa', duration: '60 days', notes: 'e-Visa required.' },
  'SG-US': { requirement: 'e_visa', duration: '90 days', notes: 'ESTA required ($21).' },
  'SG-GB': { requirement: 'visa_free', duration: '6 months', notes: 'No visa required.' },
  'SG-CN': { requirement: 'visa_free', duration: '15 days', notes: '15-day visa-free (2024 policy).' },
  'SG-AU': { requirement: 'e_visa', duration: '12 months', notes: 'eTA required (AUD$20).' },
  'SG-FR': { requirement: 'visa_free', duration: '90 days', notes: 'No visa for 90 days in Schengen area.' },
  'SG-TR': { requirement: 'visa_free', duration: '30 days', notes: 'No visa required.' },
  'SG-MV': { requirement: 'visa_free', duration: '30 days', notes: 'Free on arrival.' },
};

function stripAccents(s: string): string {
  return s.normalize('NFD').replace(/[̀-ͯ]/g, '');
}

export function getDestinationCountry(city: string): string | null {
  const key = stripAccents(city.toLowerCase().trim());
  for (const [k, v] of Object.entries(CITY_TO_COUNTRY)) {
    const nk = stripAccents(k);
    if (key.includes(nk) || nk.includes(key)) return v;
  }
  return null;
}

export function getVisaInfo(passportCode: string, destinationCity: string): VisaEntry | null {
  const destCountry = getDestinationCountry(destinationCity);
  if (!destCountry) return null;
  if (passportCode === destCountry) return { requirement: 'visa_free', duration: 'Unrestricted', notes: 'You hold a passport from this country — no visa required.' };
  const key = `${passportCode}-${destCountry}`;
  return VISA_DATA[key] || null;
}

export function getCountryName(code: string): string {
  return COUNTRIES.find(c => c.code === code)?.name ?? code;
}
